[env:esp32-s3-touch-lcd-4]
platform = espressif32
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
;build_src_filter = +<*> -<NMEA2000_Sail_Instrument.ino *.cpp>
board_build.partitions = partitions_ffat_16MB.csv
board_build.filesystem = fatfs

; --- PSRAM / Flash zgodnie z oficjalną konfiguracją Waveshare (ESP32S3 Dev Module, OPI PSRAM) ---
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.flash_size = 16MB
;board_build.partitions = default_8MB.csv   ; dopasuj do rozmiaru flash Twojej plytki (4MB/8MB/16MB)

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_INCLUDE_SIMPLE=1
    -I${PROJECT_DIR}/include

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 115200

;lib_extra_dirs =
;    lib/waveshare_libs

lib_deps =
    moononournation/GFX Library for Arduino @ ^1.4.7
    lvgl/lvgl @ ^8.3.11

upload_port = /dev/cu.usbmodem13*
monitor_port = /dev/cu.usbmodem13*
