// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"


// IMAGE DATA: assets/ZoomOut.png
lv_img_dsc_t ui_img_zoomout_png = {
    .header.always_zero = 0,
    .header.w = 36,
    .header.h = 36,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_zoomout_png_load()
{
    ui_img_zoomout_png.data = UI_LOAD_IMAGE("F:assets/ui_img_zoomout_png.bin", 3888);
    ui_img_zoomout_png.data_size = 3888;
}
