// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"


// IMAGE DATA: assets/Warning.png
lv_img_dsc_t ui_img_warning_png = {
    .header.always_zero = 0,
    .header.w = 100,
    .header.h = 93,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_warning_png_load()
{
    ui_img_warning_png.data = UI_LOAD_IMAGE("F:assets/ui_img_warning_png.bin", 27900);
    ui_img_warning_png.data_size = 27900;
}
