// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"


// IMAGE DATA: assets/Compass2.png
lv_img_dsc_t ui_img_compass2_png = {
    .header.always_zero = 0,
    .header.w = 422,
    .header.h = 422,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_compass2_png_load()
{
    ui_img_compass2_png.data = UI_LOAD_IMAGE("F:assets/ui_img_compass2_png.bin", 534252);
    ui_img_compass2_png.data_size = 534252;
}
