// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"

lv_obj_t * ui_Heading1;
lv_obj_t * ui_Rudder2;
lv_obj_t * ui_AutopilotHeading;
lv_obj_t * ui_APmode;
lv_obj_t * ui_Compass;
lv_obj_t * ui_APheadingPanel;
lv_obj_t * ui_Needle;
lv_obj_t * ui_APwindPanel;
lv_obj_t * ui_WindLbl;
lv_obj_t * ui_Wind;
lv_obj_t * ui_Track;
lv_obj_t * ui_Auto;
lv_obj_t * ui_Plus10;
lv_obj_t * ui_Plus1;
lv_obj_t * ui_Minus10;
lv_obj_t * ui_Minus1;
lv_obj_t * ui_ScrAutopilot;
lv_obj_t * ui_ScrAutopilot = NULL;
lv_obj_t * ui_Minus1 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Minus10 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Plus1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Plus10 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Auto = NULL;
lv_obj_t * ui_StandbyLbl1 = NULL;
lv_obj_t * ui_Track = NULL;
lv_obj_t * ui_StandbyLbl2 = NULL;
lv_obj_t * ui_Wind = NULL;
lv_obj_t * ui_WindLbl = NULL;
lv_obj_t * ui_APwindPanel = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Needle = NULL;
lv_obj_t * ui_APheadingPanel = NULL;
lv_obj_t * ui_Compass = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_APmode = NULL;
lv_obj_t * ui_AutopilotHeading = NULL;
lv_obj_t * ui_Rudder2 = NULL;
lv_obj_t * ui_Heading1 = NULL;
// event funtions
void ui_event_ScrAutopilot(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrWind, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScrWind_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrNav, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScrNav_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrXTE, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_ScrXTE_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrXTE, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ScrXTE_screen_init);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        DoSetBacklight(e);
    }
}

void ui_event_Minus1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        Pilot_min1(e);
    }
}

void ui_event_Minus10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        Pilot_min10(e);
    }
}

void ui_event_Plus1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        Pilot_plus1(e);
    }
}

void ui_event_Plus10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        Pilot_plus10(e);
    }
}

void ui_event_Auto(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        Auto_pressed(e);
    }
}

void ui_event_Track(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        Track_pressed(e);
    }
}

void ui_event_Wind(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        Wind_pressed(e);
    }
}

// build funtions

void ui_ScrAutopilot_screen_init(void)
{
    ui_ScrAutopilot = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrAutopilot, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags

    ui_Minus1 = lv_btn_create(ui_ScrAutopilot);
    lv_obj_set_width(ui_Minus1, 99);
    lv_obj_set_height(ui_Minus1, 69);
    lv_obj_set_x(ui_Minus1, 129);
    lv_obj_set_y(ui_Minus1, 395);
    lv_obj_clear_flag(ui_Minus1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Minus1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Minus1, lv_color_hex(0x494949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Minus1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Minus1, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Minus1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Minus1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Minus1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Minus1, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Minus1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Minus1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Minus1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Minus1, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Minus1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Minus1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Minus1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Minus1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Minus1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Minus1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Minus1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Minus1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Minus1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -2);
    lv_obj_set_y(ui_Label6, 0);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "-1");
    lv_obj_clear_flag(ui_Label6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Minus10 = lv_btn_create(ui_ScrAutopilot);
    lv_obj_set_width(ui_Minus10, 99);
    lv_obj_set_height(ui_Minus10, 69);
    lv_obj_set_x(ui_Minus10, 8);
    lv_obj_set_y(ui_Minus10, 395);
    lv_obj_clear_flag(ui_Minus10, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Minus10, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Minus10, lv_color_hex(0x494949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Minus10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Minus10, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Minus10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Minus10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Minus10, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Minus10, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Minus10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Minus10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Minus10, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Minus10, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Minus10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Minus10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Minus10, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Minus10, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Minus10, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Minus10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Minus10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Minus10, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Minus10);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -2);
    lv_obj_set_y(ui_Label8, 0);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "-10");
    lv_obj_clear_flag(ui_Label8, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Plus1 = lv_btn_create(ui_ScrAutopilot);
    lv_obj_set_width(ui_Plus1, 99);
    lv_obj_set_height(ui_Plus1, 69);
    lv_obj_set_x(ui_Plus1, 249);
    lv_obj_set_y(ui_Plus1, 395);
    lv_obj_clear_flag(ui_Plus1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Plus1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Plus1, lv_color_hex(0x494949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Plus1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Plus1, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Plus1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Plus1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Plus1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Plus1, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Plus1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Plus1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Plus1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Plus1, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Plus1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Plus1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Plus1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Plus1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Plus1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Plus1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Plus1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Plus1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Plus1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -2);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "+1");
    lv_obj_clear_flag(ui_Label2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Plus10 = lv_btn_create(ui_ScrAutopilot);
    lv_obj_set_width(ui_Plus10, 99);
    lv_obj_set_height(ui_Plus10, 69);
    lv_obj_set_x(ui_Plus10, 370);
    lv_obj_set_y(ui_Plus10, 395);
    lv_obj_clear_flag(ui_Plus10, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Plus10, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Plus10, lv_color_hex(0x494949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Plus10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Plus10, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Plus10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Plus10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Plus10, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Plus10, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Plus10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Plus10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Plus10, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Plus10, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Plus10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Plus10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Plus10, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Plus10, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Plus10, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Plus10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Plus10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Plus10, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Plus10);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -2);
    lv_obj_set_y(ui_Label3, 0);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "+10");
    lv_obj_clear_flag(ui_Label3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Auto = lv_btn_create(ui_ScrAutopilot);
    lv_obj_set_width(ui_Auto, 145);
    lv_obj_set_height(ui_Auto, 69);
    lv_obj_set_x(ui_Auto, 8);
    lv_obj_set_y(ui_Auto, 310);
    lv_obj_clear_flag(ui_Auto, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Auto, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Auto, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Auto, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Auto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Auto, lv_color_hex(0xA5A5A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Auto, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Auto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Auto, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Auto, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Auto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Auto, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Auto, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Auto, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Auto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Auto, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Auto, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Auto, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Auto, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Auto, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Auto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Auto, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Auto, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Auto, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_Auto, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Auto, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Auto, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Auto, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Auto, lv_color_hex(0x878787), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Auto, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_grad_color(ui_Auto, lv_color_hex(0xBABABA), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_grad_dir(ui_Auto, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_outline_color(ui_Auto, lv_color_hex(0x00FF80), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_outline_opa(ui_Auto, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_outline_width(ui_Auto, 5, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_outline_pad(ui_Auto, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_Auto, lv_color_hex(0x00FF80), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_Auto, 255, LV_PART_MAIN | LV_STATE_USER_1);

    ui_StandbyLbl1 = lv_label_create(ui_Auto);
    lv_obj_set_width(ui_StandbyLbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StandbyLbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StandbyLbl1, -2);
    lv_obj_set_y(ui_StandbyLbl1, 0);
    lv_obj_set_align(ui_StandbyLbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StandbyLbl1, "Auto");
    lv_obj_clear_flag(ui_StandbyLbl1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Track = lv_btn_create(ui_ScrAutopilot);
    lv_obj_set_width(ui_Track, 145);
    lv_obj_set_height(ui_Track, 69);
    lv_obj_set_x(ui_Track, 165);
    lv_obj_set_y(ui_Track, 310);
    lv_obj_clear_flag(ui_Track, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Track, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Track, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Track, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Track, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Track, lv_color_hex(0xA5A5A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Track, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Track, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Track, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Track, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Track, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Track, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Track, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Track, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Track, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Track, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Track, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Track, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Track, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Track, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Track, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Track, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Track, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Track, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_Track, lv_color_hex(0xFFA200), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_Track, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_Track, 5, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_Track, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_Track, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Track, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Track, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Track, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_Track, lv_color_hex(0xFFA200), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Track, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Track, lv_color_hex(0x878787), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Track, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_grad_color(ui_Track, lv_color_hex(0xBABABA), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_grad_dir(ui_Track, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_outline_color(ui_Track, lv_color_hex(0xFFA200), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_outline_opa(ui_Track, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_outline_width(ui_Track, 5, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_outline_pad(ui_Track, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_Track, lv_color_hex(0xFFA200), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_Track, 255, LV_PART_MAIN | LV_STATE_USER_1);

    ui_StandbyLbl2 = lv_label_create(ui_Track);
    lv_obj_set_width(ui_StandbyLbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StandbyLbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StandbyLbl2, -2);
    lv_obj_set_y(ui_StandbyLbl2, 0);
    lv_obj_set_align(ui_StandbyLbl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StandbyLbl2, "Track");
    lv_obj_clear_flag(ui_StandbyLbl2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Wind = lv_btn_create(ui_ScrAutopilot);
    lv_obj_set_width(ui_Wind, 145);
    lv_obj_set_height(ui_Wind, 69);
    lv_obj_set_x(ui_Wind, 322);
    lv_obj_set_y(ui_Wind, 310);
    lv_obj_clear_flag(ui_Wind, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Wind, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Wind, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Wind, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Wind, lv_color_hex(0xA5A5A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Wind, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Wind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Wind, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Wind, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Wind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Wind, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Wind, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Wind, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Wind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Wind, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Wind, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Wind, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Wind, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Wind, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Wind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Wind, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Wind, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Wind, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_Wind, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Wind, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Wind, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Wind, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Wind, lv_color_hex(0x878787), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Wind, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_grad_color(ui_Wind, lv_color_hex(0xBABABA), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_grad_dir(ui_Wind, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_outline_color(ui_Wind, lv_color_hex(0x00F2FF), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_outline_opa(ui_Wind, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_outline_width(ui_Wind, 5, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_outline_pad(ui_Wind, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_Wind, lv_color_hex(0x00F2FF), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_Wind, 255, LV_PART_MAIN | LV_STATE_USER_1);

    ui_WindLbl = lv_label_create(ui_Wind);
    lv_obj_set_width(ui_WindLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WindLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WindLbl, -2);
    lv_obj_set_y(ui_WindLbl, 0);
    lv_obj_set_align(ui_WindLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WindLbl, "Wind");
    lv_obj_clear_flag(ui_WindLbl, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_APwindPanel = lv_obj_create(ui_ScrAutopilot);
    lv_obj_set_width(ui_APwindPanel, 460);
    lv_obj_set_height(ui_APwindPanel, 299);
    lv_obj_set_x(ui_APwindPanel, 8);
    lv_obj_set_y(ui_APwindPanel, 2);
    lv_obj_clear_flag(ui_APwindPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_APwindPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_APwindPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_APwindPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_APwindPanel, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_APwindPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_APwindPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_APwindPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_APwindPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_APwindPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_APwindPanel);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 0);
    lv_obj_set_y(ui_Label21, -60);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "AWA");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_APwindPanel);
    lv_img_set_src(ui_Image1, &ui_img_circularscale_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, 24);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Needle = lv_img_create(ui_APwindPanel);
    lv_img_set_src(ui_Needle, &ui_img_needle2_png);
    lv_obj_set_width(ui_Needle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Needle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Needle, -4);
    lv_obj_set_y(ui_Needle, -117);
    lv_obj_set_align(ui_Needle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Needle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Needle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_Needle, 12, 174);
    lv_img_set_angle(ui_Needle, 900);

    ui_APheadingPanel = lv_obj_create(ui_ScrAutopilot);
    lv_obj_set_width(ui_APheadingPanel, 460);
    lv_obj_set_height(ui_APheadingPanel, 299);
    lv_obj_set_x(ui_APheadingPanel, 8);
    lv_obj_set_y(ui_APheadingPanel, 3);
    lv_obj_add_flag(ui_APheadingPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_APheadingPanel,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_APheadingPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_APheadingPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_APheadingPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_APheadingPanel, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_APheadingPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_APheadingPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_APheadingPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_APheadingPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_APheadingPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Compass = lv_img_create(ui_APheadingPanel);
    lv_img_set_src(ui_Compass, &ui_img_compass2_png);
    lv_obj_set_width(ui_Compass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Compass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Compass, -3);
    lv_obj_set_y(ui_Compass, 367);
    lv_obj_set_align(ui_Compass, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Compass, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_zoom(ui_Compass, 600);

    ui_Image3 = lv_img_create(ui_APheadingPanel);
    lv_img_set_src(ui_Image3, &ui_img_indicator_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 0);
    lv_obj_set_y(ui_Image3, -137);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label22 = lv_label_create(ui_APheadingPanel);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 0);
    lv_obj_set_y(ui_Label22, -63);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "HDG");
    lv_obj_clear_flag(ui_Label22, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label22, 230, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_APmode = lv_label_create(ui_ScrAutopilot);
    lv_obj_set_width(ui_APmode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_APmode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_APmode, -3);
    lv_obj_set_y(ui_APmode, -61);
    lv_obj_set_align(ui_APmode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_APmode, "--------");
    lv_obj_clear_flag(ui_APmode, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_APmode, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AutopilotHeading = lv_label_create(ui_ScrAutopilot);
    lv_obj_set_width(ui_AutopilotHeading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AutopilotHeading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AutopilotHeading, -3);
    lv_obj_set_y(ui_AutopilotHeading, -14);
    lv_obj_set_align(ui_AutopilotHeading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AutopilotHeading, "---°");
    lv_obj_clear_flag(ui_AutopilotHeading,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_AutopilotHeading, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Rudder2 = lv_bar_create(ui_ScrAutopilot);
    lv_bar_set_mode(ui_Rudder2, LV_BAR_MODE_SYMMETRICAL);
    lv_bar_set_range(ui_Rudder2, -30, 30);
    lv_obj_set_width(ui_Rudder2, 445);
    lv_obj_set_height(ui_Rudder2, 19);
    lv_obj_set_x(ui_Rudder2, -3);
    lv_obj_set_y(ui_Rudder2, 44);
    lv_obj_set_align(ui_Rudder2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Rudder2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Rudder2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Rudder2, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Rudder2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Rudder2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Rudder2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Rudder2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Rudder2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Rudder2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Rudder2, lv_color_hex(0xFB0202), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Rudder2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Rudder2, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Rudder2, 127, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Rudder2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Rudder2, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Rudder2, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Rudder2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Rudder2, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Heading1 = lv_label_create(ui_ScrAutopilot);
    lv_obj_set_width(ui_Heading1, 95);
    lv_obj_set_height(ui_Heading1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Heading1, -3);
    lv_obj_set_y(ui_Heading1, -117);
    lv_obj_set_align(ui_Heading1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Heading1, "---");
    lv_obj_clear_flag(ui_Heading1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Heading1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Heading1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Heading1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Heading1, lv_color_hex(0xEAFF01), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Heading1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Heading1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Heading1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Heading1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Minus1, ui_event_Minus1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Minus10, ui_event_Minus10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Plus1, ui_event_Plus1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Plus10, ui_event_Plus10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Auto, ui_event_Auto, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Track, ui_event_Track, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wind, ui_event_Wind, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrAutopilot, ui_event_ScrAutopilot, LV_EVENT_ALL, NULL);
    ui_ScrAutopilot = ui_ScrAutopilot;
    ui_Minus1 = ui_Minus1;
    ui_Minus10 = ui_Minus10;
    ui_Plus1 = ui_Plus1;
    ui_Plus10 = ui_Plus10;
    ui_Auto = ui_Auto;
    ui_Track = ui_Track;
    ui_Wind = ui_Wind;
    ui_WindLbl = ui_WindLbl;
    ui_APwindPanel = ui_APwindPanel;
    ui_Needle = ui_Needle;
    ui_APheadingPanel = ui_APheadingPanel;
    ui_Compass = ui_Compass;
    ui_APmode = ui_APmode;
    ui_AutopilotHeading = ui_AutopilotHeading;
    ui_Rudder2 = ui_Rudder2;
    ui_Heading1 = ui_Heading1;

}

void ui_ScrAutopilot_screen_destroy(void)
{
    if(ui_ScrAutopilot) lv_obj_del(ui_ScrAutopilot);

    // NULL screen variables
    ui_ScrAutopilot = NULL;
    ui_ScrAutopilot = NULL;
    ui_Minus1 = NULL;
    ui_Minus1 = NULL;
    ui_Label6 = NULL;
    ui_Minus10 = NULL;
    ui_Minus10 = NULL;
    ui_Label8 = NULL;
    ui_Plus1 = NULL;
    ui_Plus1 = NULL;
    ui_Label2 = NULL;
    ui_Plus10 = NULL;
    ui_Plus10 = NULL;
    ui_Label3 = NULL;
    ui_Auto = NULL;
    ui_Auto = NULL;
    ui_StandbyLbl1 = NULL;
    ui_Track = NULL;
    ui_Track = NULL;
    ui_StandbyLbl2 = NULL;
    ui_Wind = NULL;
    ui_Wind = NULL;
    ui_WindLbl = NULL;
    ui_WindLbl = NULL;
    ui_APwindPanel = NULL;
    ui_APwindPanel = NULL;
    ui_Label21 = NULL;
    ui_Image1 = NULL;
    ui_Needle = NULL;
    ui_Needle = NULL;
    ui_APheadingPanel = NULL;
    ui_APheadingPanel = NULL;
    ui_Compass = NULL;
    ui_Compass = NULL;
    ui_Image3 = NULL;
    ui_Label22 = NULL;
    ui_APmode = NULL;
    ui_APmode = NULL;
    ui_AutopilotHeading = NULL;
    ui_AutopilotHeading = NULL;
    ui_Rudder2 = NULL;
    ui_Rudder2 = NULL;
    ui_Heading1 = NULL;
    ui_Heading1 = NULL;

}
