// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"

lv_obj_t * ui_WindLbl1;
lv_obj_t * ui_Heading;
lv_obj_t * ui_GroundSpeed2;
lv_obj_t * ui_TruWindSpeed;
lv_obj_t * ui_Waterspeed;
lv_obj_t * ui_Depth1;
lv_obj_t * ui_AppWindSpeed;
lv_obj_t * ui_TrueWindImg;
lv_obj_t * ui_AppWindImg;
lv_obj_t * ui_CompassRoseImg;
lv_obj_t * ui_Contour;
lv_obj_t * ui_Rudder;
lv_obj_t * ui_ScrWind;
lv_obj_t * ui_ScrWind = NULL;
lv_obj_t * ui_Rudder = NULL;
lv_obj_t * ui_Contour = NULL;
lv_obj_t * ui_CompassRoseImg = NULL;
lv_obj_t * ui_AppWindImg = NULL;
lv_obj_t * ui_TrueWindImg = NULL;
lv_obj_t * ui_AppWindSpeed = NULL;
lv_obj_t * ui_Depth1 = NULL;
lv_obj_t * ui_Waterspeed = NULL;
lv_obj_t * ui_TruWindSpeed = NULL;
lv_obj_t * ui_GroundSpeed2 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Heading = NULL;
lv_obj_t * ui_Label38 = NULL;
lv_obj_t * ui_WindLbl1 = NULL;
// event funtions
void ui_event_ScrWind(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrAutopilot, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScrAutopilot_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrNav, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScrNav_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrAppWind, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ScrAppWind_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrTruWind, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_ScrTruWind_screen_init);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        DoSetBacklight(e);
    }
}

// build funtions

void ui_ScrWind_screen_init(void)
{
    ui_ScrWind = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrWind, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrWind, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrWind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Rudder = lv_bar_create(ui_ScrWind);
    lv_bar_set_mode(ui_Rudder, LV_BAR_MODE_SYMMETRICAL);
    lv_bar_set_range(ui_Rudder, -30, 30);
    lv_obj_set_width(ui_Rudder, 214);
    lv_obj_set_height(ui_Rudder, 19);
    lv_obj_set_x(ui_Rudder, 0);
    lv_obj_set_y(ui_Rudder, 110);
    lv_obj_set_align(ui_Rudder, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Rudder, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Rudder, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Rudder, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Rudder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Rudder, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Rudder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Rudder, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Rudder, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Rudder, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Rudder, lv_color_hex(0xFB0202), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Rudder, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Rudder, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Rudder, 127, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Rudder, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Rudder, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Rudder, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Rudder, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Rudder, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Contour = lv_img_create(ui_ScrWind);
    lv_img_set_src(ui_Contour, &ui_img_contour_png);
    lv_obj_set_width(ui_Contour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Contour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Contour, 1);
    lv_obj_set_y(ui_Contour, -117);
    lv_obj_set_align(ui_Contour, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Contour, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_CompassRoseImg = lv_img_create(ui_ScrWind);
    lv_img_set_src(ui_CompassRoseImg, &ui_img_compass2_png);
    lv_obj_set_width(ui_CompassRoseImg, LV_SIZE_CONTENT);   /// 360
    lv_obj_set_height(ui_CompassRoseImg, LV_SIZE_CONTENT);    /// 245
    lv_obj_set_align(ui_CompassRoseImg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CompassRoseImg,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_AppWindImg = lv_img_create(ui_ScrWind);
    lv_img_set_src(ui_AppWindImg, &ui_img_appwind_png);
    lv_obj_set_width(ui_AppWindImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AppWindImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AppWindImg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AppWindImg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_TrueWindImg = lv_img_create(ui_ScrWind);
    lv_img_set_src(ui_TrueWindImg, &ui_img_truewind_png);
    lv_obj_set_width(ui_TrueWindImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrueWindImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TrueWindImg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TrueWindImg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_AppWindSpeed = lv_label_create(ui_ScrWind);
    lv_obj_set_width(ui_AppWindSpeed, 150);
    lv_obj_set_height(ui_AppWindSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AppWindSpeed, 0);
    lv_obj_set_y(ui_AppWindSpeed, 12);
    lv_obj_set_align(ui_AppWindSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AppWindSpeed, "--.-");
    lv_obj_clear_flag(ui_AppWindSpeed, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_AppWindSpeed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_AppWindSpeed, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AppWindSpeed, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Depth1 = lv_label_create(ui_ScrWind);
    lv_obj_set_width(ui_Depth1, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_Depth1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Depth1, 289);
    lv_obj_set_y(ui_Depth1, 12);
    lv_label_set_text(ui_Depth1, "Depth ---.- m");
    lv_obj_clear_flag(ui_Depth1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Depth1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Depth1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Waterspeed = lv_label_create(ui_ScrWind);
    lv_obj_set_width(ui_Waterspeed, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_Waterspeed, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Waterspeed, 8);
    lv_obj_set_y(ui_Waterspeed, 436);
    lv_label_set_text(ui_Waterspeed, "STW ---- kn");
    lv_obj_clear_flag(ui_Waterspeed, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Waterspeed, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Waterspeed, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TruWindSpeed = lv_label_create(ui_ScrWind);
    lv_obj_set_width(ui_TruWindSpeed, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_TruWindSpeed, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_TruWindSpeed, 8);
    lv_obj_set_y(ui_TruWindSpeed, 12);
    lv_label_set_text(ui_TruWindSpeed, "TWS --.- kn");
    lv_obj_clear_flag(ui_TruWindSpeed, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_TruWindSpeed, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TruWindSpeed, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GroundSpeed2 = lv_label_create(ui_ScrWind);
    lv_obj_set_width(ui_GroundSpeed2, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_GroundSpeed2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_GroundSpeed2, -6);
    lv_obj_set_y(ui_GroundSpeed2, 436);
    lv_obj_set_align(ui_GroundSpeed2, LV_ALIGN_TOP_RIGHT);
    lv_label_set_long_mode(ui_GroundSpeed2, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_GroundSpeed2, "SOG --.- kn");
    lv_obj_clear_flag(ui_GroundSpeed2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_GroundSpeed2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_align(ui_GroundSpeed2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GroundSpeed2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_ScrWind);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, 89);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Rudder");
    lv_obj_clear_flag(ui_Label19, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Heading = lv_label_create(ui_ScrWind);
    lv_obj_set_width(ui_Heading, 95);
    lv_obj_set_height(ui_Heading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Heading, 0);
    lv_obj_set_y(ui_Heading, -120);
    lv_obj_set_align(ui_Heading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Heading, "---");
    lv_obj_clear_flag(ui_Heading, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Heading, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Heading, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Heading, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Heading, lv_color_hex(0xEAFF01), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Heading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Heading, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Heading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Heading, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_ScrWind);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, 0);
    lv_obj_set_y(ui_Label38, -29);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "AWS");
    lv_obj_clear_flag(ui_Label38, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WindLbl1 = lv_label_create(ui_ScrWind);
    lv_obj_set_width(ui_WindLbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WindLbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WindLbl1, 0);
    lv_obj_set_y(ui_WindLbl1, 55);
    lv_obj_set_align(ui_WindLbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WindLbl1, "knots");
    lv_obj_clear_flag(ui_WindLbl1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_WindLbl1, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WindLbl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WindLbl1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScrWind, ui_event_ScrWind, LV_EVENT_ALL, NULL);
    ui_ScrWind = ui_ScrWind;
    ui_Rudder = ui_Rudder;
    ui_Contour = ui_Contour;
    ui_CompassRoseImg = ui_CompassRoseImg;
    ui_AppWindImg = ui_AppWindImg;
    ui_TrueWindImg = ui_TrueWindImg;
    ui_AppWindSpeed = ui_AppWindSpeed;
    ui_Depth1 = ui_Depth1;
    ui_Waterspeed = ui_Waterspeed;
    ui_TruWindSpeed = ui_TruWindSpeed;
    ui_GroundSpeed2 = ui_GroundSpeed2;
    ui_Heading = ui_Heading;
    ui_WindLbl1 = ui_WindLbl1;

}

void ui_ScrWind_screen_destroy(void)
{
    if(ui_ScrWind) lv_obj_del(ui_ScrWind);

    // NULL screen variables
    ui_ScrWind = NULL;
    ui_ScrWind = NULL;
    ui_Rudder = NULL;
    ui_Rudder = NULL;
    ui_Contour = NULL;
    ui_Contour = NULL;
    ui_CompassRoseImg = NULL;
    ui_CompassRoseImg = NULL;
    ui_AppWindImg = NULL;
    ui_AppWindImg = NULL;
    ui_TrueWindImg = NULL;
    ui_TrueWindImg = NULL;
    ui_AppWindSpeed = NULL;
    ui_AppWindSpeed = NULL;
    ui_Depth1 = NULL;
    ui_Depth1 = NULL;
    ui_Waterspeed = NULL;
    ui_Waterspeed = NULL;
    ui_TruWindSpeed = NULL;
    ui_TruWindSpeed = NULL;
    ui_GroundSpeed2 = NULL;
    ui_GroundSpeed2 = NULL;
    ui_Label19 = NULL;
    ui_Heading = NULL;
    ui_Heading = NULL;
    ui_Label38 = NULL;
    ui_WindLbl1 = NULL;
    ui_WindLbl1 = NULL;

}
