// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_img_splash_png_load();
    ui_img_contour_png_load();
    ui_img_compass2_png_load();
    ui_img_appwind_png_load();
    ui_img_truewind_png_load();
    ui_img_circularscale_png_load();
    ui_img_needle2_png_load();
    ui_img_indicator_png_load();
    ui_img_helmman_png_load();
    ui_img_boat_png_load();
    ui_img_1883567225_load();
    ui_img_zoomin_png_load();
    ui_img_windcontour_png_load();
    ui_img_circcaleclosehaul_png_load();
    ui_img_needle_png_load();
    ui_img_warning_png_load();
    ui_img_settings_png_load();
    ui_img_ok_png_load();
    ui_img_cancel_png_load();
    ui_img_turn_starboard_png_load();
    ui_img_brightness_png_load();
    ui_img_error_png_load();
    ui_img_error2_png_load();
    ui_img_zoomout_png_load();
    ui_img_turn_port_png_load();
    ui_SplashScr_screen_init();
    ui_ScrWind_screen_init();
    ui_ScrAutopilot_screen_init();
    ui_ScrXTE_screen_init();
    ui_ScrNav_screen_init();
    ui_ScrAppWind_screen_init();
    ui_ScrTruWind_screen_init();
    ui_ScrInfo_screen_init();
    ui_SettingsScr_screen_init();
    ui_DialogScr_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_SplashScr);
}

void ui_destroy(void)
{
    ui_SplashScr_screen_destroy();
    ui_ScrWind_screen_destroy();
    ui_ScrAutopilot_screen_destroy();
    ui_ScrXTE_screen_destroy();
    ui_ScrNav_screen_destroy();
    ui_ScrAppWind_screen_destroy();
    ui_ScrTruWind_screen_destroy();
    ui_ScrInfo_screen_destroy();
    ui_SettingsScr_screen_destroy();
    ui_DialogScr_screen_destroy();
}
