// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#ifndef _NMEA2000SAILINSTRUMENT_UI_H
#define _NMEA2000SAILINSTRUMENT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

#include "ui_img_manager.h"

///////////////////// SCREENS ////////////////////
#include "ui_SplashScr.h"
#include "ui_ScrWind.h"
#include "ui_ScrAutopilot.h"
#include "ui_ScrXTE.h"
#include "ui_ScrNav.h"
#include "ui_ScrAppWind.h"
#include "ui_ScrTruWind.h"
#include "ui_ScrInfo.h"
#include "ui_SettingsScr.h"
#include "ui_DialogScr.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
extern lv_img_dsc_t ui_img_splash_png;   // assets/Splash.png
void ui_img_splash_png_load();
extern lv_img_dsc_t ui_img_contour_png;   // assets/Contour.png
void ui_img_contour_png_load();
extern lv_img_dsc_t ui_img_compass2_png;   // assets/Compass2.png
void ui_img_compass2_png_load();
extern lv_img_dsc_t ui_img_appwind_png;   // assets/AppWind.png
void ui_img_appwind_png_load();
extern lv_img_dsc_t ui_img_truewind_png;   // assets/TrueWind.png
void ui_img_truewind_png_load();
extern lv_img_dsc_t ui_img_circularscale_png;   // assets/circularscale.png
void ui_img_circularscale_png_load();
extern lv_img_dsc_t ui_img_needle2_png;   // assets/Needle2.png
void ui_img_needle2_png_load();
extern lv_img_dsc_t ui_img_indicator_png;   // assets/Indicator.png
void ui_img_indicator_png_load();
extern lv_img_dsc_t ui_img_helmman_png;   // assets/HelmMan.png
void ui_img_helmman_png_load();
extern lv_img_dsc_t ui_img_boat_png;   // assets/boat.png
void ui_img_boat_png_load();
extern lv_img_dsc_t ui_img_1883567225;   // assets/long-arrow-left.png
void ui_img_1883567225_load();
extern lv_img_dsc_t ui_img_zoomin_png;   // assets/ZoomIn.png
void ui_img_zoomin_png_load();
extern lv_img_dsc_t ui_img_windcontour_png;   // assets/WindContour.png
void ui_img_windcontour_png_load();
extern lv_img_dsc_t ui_img_circcaleclosehaul_png;   // assets/circcaleCloseHaul.png
void ui_img_circcaleclosehaul_png_load();
extern lv_img_dsc_t ui_img_needle_png;   // assets/needle.png
void ui_img_needle_png_load();
extern lv_img_dsc_t ui_img_warning_png;   // assets/Warning.png
void ui_img_warning_png_load();
extern lv_img_dsc_t ui_img_settings_png;   // assets/settings.png
void ui_img_settings_png_load();
extern lv_img_dsc_t ui_img_ok_png;   // assets/ok.png
void ui_img_ok_png_load();
extern lv_img_dsc_t ui_img_cancel_png;   // assets/cancel.png
void ui_img_cancel_png_load();
extern lv_img_dsc_t ui_img_turn_starboard_png;   // assets/turn_starboard.png
void ui_img_turn_starboard_png_load();
extern lv_img_dsc_t ui_img_brightness_png;   // assets/brightness.png
void ui_img_brightness_png_load();
extern lv_img_dsc_t ui_img_error_png;   // assets/Error.png
void ui_img_error_png_load();
extern lv_img_dsc_t ui_img_error2_png;   // assets/Error2.png
void ui_img_error2_png_load();
extern lv_img_dsc_t ui_img_zoomout_png;   // assets/ZoomOut.png
void ui_img_zoomout_png_load();
extern lv_img_dsc_t ui_img_turn_port_png;   // assets/turn_port.png
void ui_img_turn_port_png_load();

// FONTS
LV_FONT_DECLARE(ui_font_Arial60);
LV_FONT_DECLARE(ui_font_Arial90);
LV_FONT_DECLARE(ui_font_HandWriting);
LV_FONT_DECLARE(ui_font_HandWriting24);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
