// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#ifndef UI_DIALOGSCR_H
#define UI_DIALOGSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DialogScr
extern void ui_DialogScr_screen_init(void);
extern void ui_DialogScr_screen_destroy(void);
extern lv_obj_t * ui_DialogScr;
extern lv_obj_t * ui_WarningPanel;
extern lv_obj_t * ui_WarningText;
extern void ui_event_WarningOK(lv_event_t * e);
extern lv_obj_t * ui_WarningOK;
extern void ui_event_WarningCancel(lv_event_t * e);
extern lv_obj_t * ui_WarningCancel;
extern lv_obj_t * ui_WarningText1;
extern lv_obj_t * ui_WarningSymbol;
extern lv_obj_t * ui_BacklightPanel;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_BacklightSlider;
// CUSTOM VARIABLES
extern lv_obj_t * ui_DialogScr;
extern lv_obj_t * ui_WarningPanel;
extern lv_obj_t * ui_WarningText;
extern lv_obj_t * ui_WarningOK;
extern lv_obj_t * ui_WarningCancel;
extern lv_obj_t * ui_WarningText1;
extern lv_obj_t * ui_WarningSymbol;
extern lv_obj_t * ui_BacklightPanel;
extern lv_obj_t * ui_BacklightSlider;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

