// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"

lv_obj_t * ui_BacklightSlider;
lv_obj_t * ui_BacklightPanel;
lv_obj_t * ui_WarningSymbol;
lv_obj_t * ui_WarningText1;
lv_obj_t * ui_WarningCancel;
lv_obj_t * ui_WarningOK;
lv_obj_t * ui_WarningText;
lv_obj_t * ui_WarningPanel;
lv_obj_t * ui_DialogScr;
lv_obj_t * ui_DialogScr = NULL;
lv_obj_t * ui_WarningPanel = NULL;
lv_obj_t * ui_WarningText = NULL;
lv_obj_t * ui_WarningOK = NULL;
lv_obj_t * ui_WarningCancel = NULL;
lv_obj_t * ui_WarningText1 = NULL;
lv_obj_t * ui_WarningSymbol = NULL;
lv_obj_t * ui_BacklightPanel = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_BacklightSlider = NULL;
// event funtions
void ui_event_WarningOK(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        DialogOK(e);
    }
}

void ui_event_WarningCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        DialogCancel(e);
    }
}

// build funtions

void ui_DialogScr_screen_init(void)
{
    ui_DialogScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DialogScr, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_DialogScr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DialogScr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarningPanel = lv_obj_create(ui_DialogScr);
    lv_obj_set_width(ui_WarningPanel, 360);
    lv_obj_set_height(ui_WarningPanel, 351);
    lv_obj_set_x(ui_WarningPanel, 59);
    lv_obj_set_y(ui_WarningPanel, 53);
    lv_obj_clear_flag(ui_WarningPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WarningPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarningPanel, lv_color_hex(0x9BC6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarningPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WarningPanel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WarningPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WarningPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarningText = lv_label_create(ui_WarningPanel);
    lv_obj_set_width(ui_WarningText, 170);
    lv_obj_set_height(ui_WarningText, 152);
    lv_obj_set_x(ui_WarningText, 151);
    lv_obj_set_y(ui_WarningText, 17);
    lv_label_set_text(ui_WarningText, "Warning");
    lv_obj_set_style_text_align(ui_WarningText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WarningText, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarningOK = lv_btn_create(ui_WarningPanel);
    lv_obj_set_width(ui_WarningOK, 99);
    lv_obj_set_height(ui_WarningOK, 55);
    lv_obj_set_x(ui_WarningOK, 233);
    lv_obj_set_y(ui_WarningOK, 268);
    lv_obj_clear_flag(ui_WarningOK, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_WarningOK, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarningOK, lv_color_hex(0x494949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarningOK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_WarningOK, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_WarningOK, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_WarningOK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_WarningOK, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_WarningOK, &ui_img_ok_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WarningOK, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WarningOK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WarningOK, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WarningOK, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WarningOK, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WarningOK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WarningOK, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WarningOK, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_WarningOK, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_WarningOK, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WarningOK, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WarningOK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WarningOK, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarningCancel = lv_btn_create(ui_WarningPanel);
    lv_obj_set_width(ui_WarningCancel, 99);
    lv_obj_set_height(ui_WarningCancel, 55);
    lv_obj_set_x(ui_WarningCancel, -13);
    lv_obj_set_y(ui_WarningCancel, 268);
    lv_obj_clear_flag(ui_WarningCancel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_WarningCancel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarningCancel, lv_color_hex(0x494949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarningCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_WarningCancel, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_WarningCancel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_WarningCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_WarningCancel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_WarningCancel, &ui_img_cancel_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WarningCancel, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WarningCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WarningCancel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WarningCancel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WarningCancel, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WarningCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WarningCancel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WarningCancel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_WarningCancel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_WarningCancel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WarningCancel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WarningCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WarningCancel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarningText1 = lv_label_create(ui_WarningPanel);
    lv_obj_set_width(ui_WarningText1, 300);
    lv_obj_set_height(ui_WarningText1, 85);
    lv_obj_set_x(ui_WarningText1, 20);
    lv_obj_set_y(ui_WarningText1, 174);
    lv_label_set_text(ui_WarningText1, "Warning");
    lv_obj_set_style_text_align(ui_WarningText1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WarningText1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarningSymbol = lv_img_create(ui_WarningPanel);
    lv_img_set_src(ui_WarningSymbol, &ui_img_turn_starboard_png);
    lv_obj_set_width(ui_WarningSymbol, LV_SIZE_CONTENT);   /// 101
    lv_obj_set_height(ui_WarningSymbol, LV_SIZE_CONTENT);    /// 101
    lv_obj_set_x(ui_WarningSymbol, 16);
    lv_obj_set_y(ui_WarningSymbol, 35);
    lv_obj_add_flag(ui_WarningSymbol, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WarningSymbol, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WarningSymbol, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarningSymbol, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarningSymbol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BacklightPanel = lv_obj_create(ui_DialogScr);
    lv_obj_set_width(ui_BacklightPanel, 386);
    lv_obj_set_height(ui_BacklightPanel, 132);
    lv_obj_set_align(ui_BacklightPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BacklightPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BacklightPanel, lv_color_hex(0x7ACDFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BacklightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_BacklightPanel);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -34);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Backlight");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_BacklightPanel);
    lv_img_set_src(ui_Image4, &ui_img_brightness_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 145);
    lv_obj_set_y(ui_Image4, -16);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 300);

    ui_Image7 = lv_img_create(ui_BacklightPanel);
    lv_img_set_src(ui_Image7, &ui_img_brightness_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, -145);
    lv_obj_set_y(ui_Image7, -16);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 200);

    ui_BacklightSlider = lv_slider_create(ui_BacklightPanel);
    lv_slider_set_range(ui_BacklightSlider, 50, 255);
    lv_slider_set_value(ui_BacklightSlider, 255, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BacklightSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BacklightSlider, 50,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_BacklightSlider, 314);
    lv_obj_set_height(ui_BacklightSlider, 28);
    lv_obj_set_x(ui_BacklightSlider, 0);
    lv_obj_set_y(ui_BacklightSlider, 31);
    lv_obj_set_align(ui_BacklightSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_BacklightSlider, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BacklightSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BacklightSlider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_BacklightSlider, lv_color_hex(0x0000FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BacklightSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BacklightSlider, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_BacklightSlider, lv_color_hex(0x0000FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BacklightSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BacklightSlider, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WarningOK, ui_event_WarningOK, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WarningCancel, ui_event_WarningCancel, LV_EVENT_ALL, NULL);
    ui_DialogScr = ui_DialogScr;
    ui_WarningPanel = ui_WarningPanel;
    ui_WarningText = ui_WarningText;
    ui_WarningOK = ui_WarningOK;
    ui_WarningCancel = ui_WarningCancel;
    ui_WarningText1 = ui_WarningText1;
    ui_WarningSymbol = ui_WarningSymbol;
    ui_BacklightPanel = ui_BacklightPanel;
    ui_BacklightSlider = ui_BacklightSlider;

}

void ui_DialogScr_screen_destroy(void)
{
    if(ui_DialogScr) lv_obj_del(ui_DialogScr);

    // NULL screen variables
    ui_DialogScr = NULL;
    ui_DialogScr = NULL;
    ui_WarningPanel = NULL;
    ui_WarningPanel = NULL;
    ui_WarningText = NULL;
    ui_WarningText = NULL;
    ui_WarningOK = NULL;
    ui_WarningOK = NULL;
    ui_WarningCancel = NULL;
    ui_WarningCancel = NULL;
    ui_WarningText1 = NULL;
    ui_WarningText1 = NULL;
    ui_WarningSymbol = NULL;
    ui_WarningSymbol = NULL;
    ui_BacklightPanel = NULL;
    ui_BacklightPanel = NULL;
    ui_Label1 = NULL;
    ui_Image4 = NULL;
    ui_Image7 = NULL;
    ui_BacklightSlider = NULL;
    ui_BacklightSlider = NULL;

}
