// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#ifndef UI_SCRNAV_H
#define UI_SCRNAV_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrNav
extern void ui_ScrNav_screen_init(void);
extern void ui_ScrNav_screen_destroy(void);
extern void ui_event_ScrNav(lv_event_t * e);
extern lv_obj_t * ui_ScrNav;
extern lv_obj_t * ui_POSpanel;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Lat;
extern lv_obj_t * ui_Lon;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_PosLbl;
extern lv_obj_t * ui_HDGpanel;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_HDG;
extern lv_obj_t * ui_STWpanel;
extern lv_obj_t * ui_STW;
extern lv_obj_t * ui_SpeedLbl1;
extern lv_obj_t * ui_POSpanel4;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_APmode1;
extern lv_obj_t * ui_AutopilotHeading1;
// CUSTOM VARIABLES
extern lv_obj_t * ui_ScrNav;
extern lv_obj_t * ui_Lat;
extern lv_obj_t * ui_Lon;
extern lv_obj_t * ui_PosLbl;
extern lv_obj_t * ui_HDG;
extern lv_obj_t * ui_STW;
extern lv_obj_t * ui_SpeedLbl1;
extern lv_obj_t * ui_APmode1;
extern lv_obj_t * ui_AutopilotHeading1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

