// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#ifndef UI_SCRWIND_H
#define UI_SCRWIND_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrWind
extern void ui_ScrWind_screen_init(void);
extern void ui_ScrWind_screen_destroy(void);
extern void ui_event_ScrWind(lv_event_t * e);
extern lv_obj_t * ui_ScrWind;
extern lv_obj_t * ui_Rudder;
extern lv_obj_t * ui_Contour;
extern lv_obj_t * ui_CompassRoseImg;
extern lv_obj_t * ui_AppWindImg;
extern lv_obj_t * ui_TrueWindImg;
extern lv_obj_t * ui_AppWindSpeed;
extern lv_obj_t * ui_Depth1;
extern lv_obj_t * ui_Waterspeed;
extern lv_obj_t * ui_TruWindSpeed;
extern lv_obj_t * ui_GroundSpeed2;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Heading;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_WindLbl1;
// CUSTOM VARIABLES
extern lv_obj_t * ui_ScrWind;
extern lv_obj_t * ui_Rudder;
extern lv_obj_t * ui_Contour;
extern lv_obj_t * ui_CompassRoseImg;
extern lv_obj_t * ui_AppWindImg;
extern lv_obj_t * ui_TrueWindImg;
extern lv_obj_t * ui_AppWindSpeed;
extern lv_obj_t * ui_Depth1;
extern lv_obj_t * ui_Waterspeed;
extern lv_obj_t * ui_TruWindSpeed;
extern lv_obj_t * ui_GroundSpeed2;
extern lv_obj_t * ui_Heading;
extern lv_obj_t * ui_WindLbl1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

