// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#ifndef UI_SCRINFO_H
#define UI_SCRINFO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrInfo
extern void ui_ScrInfo_screen_init(void);
extern void ui_ScrInfo_screen_destroy(void);
extern void ui_event_ScrInfo(lv_event_t * e);
extern lv_obj_t * ui_ScrInfo;
extern lv_obj_t * ui_POSpanel3;
extern lv_obj_t * ui_Depth;
extern lv_obj_t * ui_DepthLbl;
extern lv_obj_t * ui_POSpanel2;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Rudder1;
extern lv_obj_t * ui_SOGpanel2;
extern lv_obj_t * ui_SOG;
extern lv_obj_t * ui_SpeedLbl;
extern lv_obj_t * ui_HDGpanel2;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_COG;
extern lv_obj_t * ui_POSpanel5;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_AWA;
extern void ui_event_Go2SettingScr(lv_event_t * e);
extern lv_obj_t * ui_Go2SettingScr;
extern lv_obj_t * ui_Auto2;
extern lv_obj_t * ui_AuthorLbl;
// CUSTOM VARIABLES
extern lv_obj_t * ui_ScrInfo;
extern lv_obj_t * ui_Depth;
extern lv_obj_t * ui_DepthLbl;
extern lv_obj_t * ui_Rudder1;
extern lv_obj_t * ui_SOG;
extern lv_obj_t * ui_SpeedLbl;
extern lv_obj_t * ui_COG;
extern lv_obj_t * ui_AWA;
extern lv_obj_t * ui_Go2SettingScr;
extern lv_obj_t * ui_AuthorLbl;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

