// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#ifndef UI_SETTINGSSCR_H
#define UI_SETTINGSSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsScr
extern void ui_SettingsScr_screen_init(void);
extern void ui_SettingsScr_screen_destroy(void);
extern lv_obj_t * ui_SettingsScr;
extern lv_obj_t * ui_POSpanel6;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_SpeedDropdown;
extern lv_obj_t * ui_PostionDropdown;
extern lv_obj_t * ui_DistanceDropdown;
extern lv_obj_t * ui_WindDropdown;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_WindDampingSlider;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_HeadingDampingSlider;
extern void ui_event_SettingsOk(lv_event_t * e);
extern lv_obj_t * ui_SettingsOk;
extern void ui_event_SettingsCancel(lv_event_t * e);
extern lv_obj_t * ui_SettingsCancel;
extern lv_obj_t * ui_DepthDropdown;
extern lv_obj_t * ui_AutoSilenceNoPilot;
// CUSTOM VARIABLES
extern lv_obj_t * ui_SettingsScr;
extern lv_obj_t * ui_SpeedDropdown;
extern lv_obj_t * ui_PostionDropdown;
extern lv_obj_t * ui_DistanceDropdown;
extern lv_obj_t * ui_WindDropdown;
extern lv_obj_t * ui_WindDampingSlider;
extern lv_obj_t * ui_HeadingDampingSlider;
extern lv_obj_t * ui_SettingsOk;
extern lv_obj_t * ui_SettingsCancel;
extern lv_obj_t * ui_DepthDropdown;
extern lv_obj_t * ui_AutoSilenceNoPilot;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

