// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#ifndef UI_SCRXTE_H
#define UI_SCRXTE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrXTE
extern void ui_ScrXTE_screen_init(void);
extern void ui_ScrXTE_screen_destroy(void);
extern void ui_event_ScrXTE(lv_event_t * e);
extern lv_obj_t * ui_ScrXTE;
extern lv_obj_t * ui_HelmManPanel;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_BoatImg;
extern lv_obj_t * ui_BTWpanel;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_BearingWpt;
extern lv_obj_t * ui_XTEpanel;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_XTEright;
extern lv_obj_t * ui_XTEleft;
extern lv_obj_t * ui_XteWpt;
extern lv_obj_t * ui_DistanceLbl;
extern lv_obj_t * ui_DTWpanel;
extern lv_obj_t * ui_DistanceWpt;
extern lv_obj_t * ui_DistanceLbl1;
extern lv_obj_t * ui_ETWpanel;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_ETW;
extern lv_obj_t * ui_ETWday;
// CUSTOM VARIABLES
extern lv_obj_t * ui_ScrXTE;
extern lv_obj_t * ui_HelmManPanel;
extern lv_obj_t * ui_BoatImg;
extern lv_obj_t * ui_BTWpanel;
extern lv_obj_t * ui_BearingWpt;
extern lv_obj_t * ui_XTEpanel;
extern lv_obj_t * ui_XTEright;
extern lv_obj_t * ui_XTEleft;
extern lv_obj_t * ui_XteWpt;
extern lv_obj_t * ui_DistanceLbl;
extern lv_obj_t * ui_DTWpanel;
extern lv_obj_t * ui_DistanceWpt;
extern lv_obj_t * ui_DistanceLbl1;
extern lv_obj_t * ui_ETWpanel;
extern lv_obj_t * ui_ETW;
extern lv_obj_t * ui_ETWday;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

