// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#ifndef UI_SCRAUTOPILOT_H
#define UI_SCRAUTOPILOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrAutopilot
extern void ui_ScrAutopilot_screen_init(void);
extern void ui_ScrAutopilot_screen_destroy(void);
extern void ui_event_ScrAutopilot(lv_event_t * e);
extern lv_obj_t * ui_ScrAutopilot;
extern void ui_event_Minus1(lv_event_t * e);
extern lv_obj_t * ui_Minus1;
extern lv_obj_t * ui_Label6;
extern void ui_event_Minus10(lv_event_t * e);
extern lv_obj_t * ui_Minus10;
extern lv_obj_t * ui_Label8;
extern void ui_event_Plus1(lv_event_t * e);
extern lv_obj_t * ui_Plus1;
extern lv_obj_t * ui_Label2;
extern void ui_event_Plus10(lv_event_t * e);
extern lv_obj_t * ui_Plus10;
extern lv_obj_t * ui_Label3;
extern void ui_event_Auto(lv_event_t * e);
extern lv_obj_t * ui_Auto;
extern lv_obj_t * ui_StandbyLbl1;
extern void ui_event_Track(lv_event_t * e);
extern lv_obj_t * ui_Track;
extern lv_obj_t * ui_StandbyLbl2;
extern void ui_event_Wind(lv_event_t * e);
extern lv_obj_t * ui_Wind;
extern lv_obj_t * ui_WindLbl;
extern lv_obj_t * ui_APwindPanel;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Needle;
extern lv_obj_t * ui_APheadingPanel;
extern lv_obj_t * ui_Compass;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_APmode;
extern lv_obj_t * ui_AutopilotHeading;
extern lv_obj_t * ui_Rudder2;
extern lv_obj_t * ui_Heading1;
// CUSTOM VARIABLES
extern lv_obj_t * ui_ScrAutopilot;
extern lv_obj_t * ui_Minus1;
extern lv_obj_t * ui_Minus10;
extern lv_obj_t * ui_Plus1;
extern lv_obj_t * ui_Plus10;
extern lv_obj_t * ui_Auto;
extern lv_obj_t * ui_Track;
extern lv_obj_t * ui_Wind;
extern lv_obj_t * ui_WindLbl;
extern lv_obj_t * ui_APwindPanel;
extern lv_obj_t * ui_Needle;
extern lv_obj_t * ui_APheadingPanel;
extern lv_obj_t * ui_Compass;
extern lv_obj_t * ui_APmode;
extern lv_obj_t * ui_AutopilotHeading;
extern lv_obj_t * ui_Rudder2;
extern lv_obj_t * ui_Heading1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

