// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"

lv_obj_t * ui_Depth4;
lv_obj_t * ui_AppWindAngle1;
lv_obj_t * ui_GroundSpeed1;
lv_obj_t * ui_WaterSpeed3;
lv_obj_t * ui_TWAneedle;
lv_obj_t * ui_WindLbl4;
lv_obj_t * ui_TWS;
lv_obj_t * ui_ScrTruWind;
lv_obj_t * ui_ScrTruWind = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_TWS = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_WindLbl4 = NULL;
lv_obj_t * ui_TWAneedle = NULL;
lv_obj_t * ui_WaterSpeed3 = NULL;
lv_obj_t * ui_GroundSpeed1 = NULL;
lv_obj_t * ui_AppWindAngle1 = NULL;
lv_obj_t * ui_Depth4 = NULL;
// event funtions
void ui_event_ScrTruWind(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrAutopilot, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScrAutopilot_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrNav, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScrNav_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrWind, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ScrWind_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrAppWind, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_ScrAppWind_screen_init);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        DoSetBacklight(e);
    }
}

// build funtions

void ui_ScrTruWind_screen_init(void)
{
    ui_ScrTruWind = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrTruWind, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrTruWind, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrTruWind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_ScrTruWind);
    lv_img_set_src(ui_Image6, &ui_img_windcontour_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, 0);
    lv_obj_set_y(ui_Image6, -3);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label20 = lv_label_create(ui_ScrTruWind);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 2);
    lv_obj_set_y(ui_Label20, -81);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "TWA");
    lv_obj_clear_flag(ui_Label20, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x828382), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TWS = lv_label_create(ui_ScrTruWind);
    lv_obj_set_width(ui_TWS, 150);
    lv_obj_set_height(ui_TWS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TWS, 0);
    lv_obj_set_y(ui_TWS, 91);
    lv_obj_set_align(ui_TWS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TWS, "--.-");
    lv_obj_clear_flag(ui_TWS, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_TWS, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TWS, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TWS, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_ScrTruWind);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, 53);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "TWS");
    lv_obj_clear_flag(ui_Label15, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label15, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WindLbl4 = lv_label_create(ui_ScrTruWind);
    lv_obj_set_width(ui_WindLbl4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WindLbl4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WindLbl4, 0);
    lv_obj_set_y(ui_WindLbl4, 133);
    lv_obj_set_align(ui_WindLbl4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WindLbl4, "knots");
    lv_obj_clear_flag(ui_WindLbl4, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_WindLbl4, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WindLbl4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WindLbl4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TWAneedle = lv_img_create(ui_ScrTruWind);
    lv_img_set_src(ui_TWAneedle, &ui_img_needle_png);
    lv_obj_set_width(ui_TWAneedle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TWAneedle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TWAneedle, -2);
    lv_obj_set_y(ui_TWAneedle, -65);
    lv_obj_set_align(ui_TWAneedle, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TWAneedle, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_pivot(ui_TWAneedle, 34, 175);

    ui_WaterSpeed3 = lv_label_create(ui_ScrTruWind);
    lv_obj_set_width(ui_WaterSpeed3, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_WaterSpeed3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_WaterSpeed3, 8);
    lv_obj_set_y(ui_WaterSpeed3, 436);
    lv_label_set_long_mode(ui_WaterSpeed3, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_WaterSpeed3, "STW --.- kn");
    lv_obj_clear_flag(ui_WaterSpeed3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_WaterSpeed3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_align(ui_WaterSpeed3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WaterSpeed3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GroundSpeed1 = lv_label_create(ui_ScrTruWind);
    lv_obj_set_width(ui_GroundSpeed1, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_GroundSpeed1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_GroundSpeed1, -6);
    lv_obj_set_y(ui_GroundSpeed1, 436);
    lv_obj_set_align(ui_GroundSpeed1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_long_mode(ui_GroundSpeed1, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_GroundSpeed1, "SOG --.- kn");
    lv_obj_clear_flag(ui_GroundSpeed1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_GroundSpeed1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_align(ui_GroundSpeed1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GroundSpeed1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AppWindAngle1 = lv_label_create(ui_ScrTruWind);
    lv_obj_set_width(ui_AppWindAngle1, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_AppWindAngle1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_AppWindAngle1, 8);
    lv_obj_set_y(ui_AppWindAngle1, 12);
    lv_label_set_text(ui_AppWindAngle1, "AWA ----");
    lv_obj_clear_flag(ui_AppWindAngle1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_AppWindAngle1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AppWindAngle1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Depth4 = lv_label_create(ui_ScrTruWind);
    lv_obj_set_width(ui_Depth4, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_Depth4, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Depth4, 289);
    lv_obj_set_y(ui_Depth4, 12);
    lv_label_set_text(ui_Depth4, "Depth ---.- m");
    lv_obj_clear_flag(ui_Depth4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Depth4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Depth4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScrTruWind, ui_event_ScrTruWind, LV_EVENT_ALL, NULL);
    ui_ScrTruWind = ui_ScrTruWind;
    ui_TWS = ui_TWS;
    ui_WindLbl4 = ui_WindLbl4;
    ui_TWAneedle = ui_TWAneedle;
    ui_WaterSpeed3 = ui_WaterSpeed3;
    ui_GroundSpeed1 = ui_GroundSpeed1;
    ui_AppWindAngle1 = ui_AppWindAngle1;
    ui_Depth4 = ui_Depth4;

}

void ui_ScrTruWind_screen_destroy(void)
{
    if(ui_ScrTruWind) lv_obj_del(ui_ScrTruWind);

    // NULL screen variables
    ui_ScrTruWind = NULL;
    ui_ScrTruWind = NULL;
    ui_Image6 = NULL;
    ui_Label20 = NULL;
    ui_TWS = NULL;
    ui_TWS = NULL;
    ui_Label15 = NULL;
    ui_WindLbl4 = NULL;
    ui_WindLbl4 = NULL;
    ui_TWAneedle = NULL;
    ui_TWAneedle = NULL;
    ui_WaterSpeed3 = NULL;
    ui_WaterSpeed3 = NULL;
    ui_GroundSpeed1 = NULL;
    ui_GroundSpeed1 = NULL;
    ui_AppWindAngle1 = NULL;
    ui_AppWindAngle1 = NULL;
    ui_Depth4 = NULL;
    ui_Depth4 = NULL;

}
