// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void DoSetBacklight(lv_event_t * e);
void Pilot_min1(lv_event_t * e);
void Pilot_min10(lv_event_t * e);
void Pilot_plus1(lv_event_t * e);
void Pilot_plus10(lv_event_t * e);
void Auto_pressed(lv_event_t * e);
void Track_pressed(lv_event_t * e);
void Wind_pressed(lv_event_t * e);
void BeepOnce(lv_event_t * e);
void DoInitSettingsScr(lv_event_t * e);
void StoreUnitSettings(lv_event_t * e);
void CancelUnitSettings(lv_event_t * e);
void DialogOK(lv_event_t * e);
void DialogCancel(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
