// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#ifndef UI_SCRTRUWIND_H
#define UI_SCRTRUWIND_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrTruWind
extern void ui_ScrTruWind_screen_init(void);
extern void ui_ScrTruWind_screen_destroy(void);
extern void ui_event_ScrTruWind(lv_event_t * e);
extern lv_obj_t * ui_ScrTruWind;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_TWS;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_WindLbl4;
extern lv_obj_t * ui_TWAneedle;
extern lv_obj_t * ui_WaterSpeed3;
extern lv_obj_t * ui_GroundSpeed1;
extern lv_obj_t * ui_AppWindAngle1;
extern lv_obj_t * ui_Depth4;
// CUSTOM VARIABLES
extern lv_obj_t * ui_ScrTruWind;
extern lv_obj_t * ui_TWS;
extern lv_obj_t * ui_WindLbl4;
extern lv_obj_t * ui_TWAneedle;
extern lv_obj_t * ui_WaterSpeed3;
extern lv_obj_t * ui_GroundSpeed1;
extern lv_obj_t * ui_AppWindAngle1;
extern lv_obj_t * ui_Depth4;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

