// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#ifndef UI_SCRAPPWIND_H
#define UI_SCRAPPWIND_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrAppWind
extern void ui_ScrAppWind_screen_init(void);
extern void ui_ScrAppWind_screen_destroy(void);
extern void ui_event_ScrAppWind(lv_event_t * e);
extern lv_obj_t * ui_ScrAppWind;
extern lv_obj_t * ui_Label24;
extern void ui_event_AWAscaletoggle(lv_event_t * e);
extern lv_obj_t * ui_AWAscaletoggle;
extern lv_obj_t * ui_AWANormalScale;
extern lv_obj_t * ui_AWACloseScale;
extern lv_obj_t * ui_AWS;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_WindLbl3;
extern lv_obj_t * ui_AWAneedle;
extern lv_obj_t * ui_WaterSpeed2;
extern lv_obj_t * ui_GroundSpeed;
extern lv_obj_t * ui_TruWindAngle2;
extern lv_obj_t * ui_Depth3;
extern lv_obj_t * ui_Warning;
// CUSTOM VARIABLES
extern lv_obj_t * ui_ScrAppWind;
extern lv_obj_t * ui_AWAscaletoggle;
extern lv_obj_t * ui_AWANormalScale;
extern lv_obj_t * ui_AWACloseScale;
extern lv_obj_t * ui_AWS;
extern lv_obj_t * ui_WindLbl3;
extern lv_obj_t * ui_AWAneedle;
extern lv_obj_t * ui_WaterSpeed2;
extern lv_obj_t * ui_GroundSpeed;
extern lv_obj_t * ui_Depth3;
extern lv_obj_t * ui_Warning;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

