// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"


// IMAGE DATA: assets/brightness.png
lv_img_dsc_t ui_img_brightness_png = {
    .header.always_zero = 0,
    .header.w = 40,
    .header.h = 39,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_brightness_png_load()
{
    ui_img_brightness_png.data = UI_LOAD_IMAGE("F:assets/ui_img_brightness_png.bin", 4680);
    ui_img_brightness_png.data_size = 4680;
}
