// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"


// IMAGE DATA: assets/HelmMan.png
lv_img_dsc_t ui_img_helmman_png = {
    .header.always_zero = 0,
    .header.w = 478,
    .header.h = 232,
    .header.cf = LV_IMG_CF_TRUE_COLOR,
};

void ui_img_helmman_png_load()
{
    ui_img_helmman_png.data = UI_LOAD_IMAGE("F:assets/ui_img_helmman_png.bin", 221792);
    ui_img_helmman_png.data_size = 221792;
}
