// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"


// IMAGE DATA: assets/long-arrow-left.png
lv_img_dsc_t ui_img_1883567225 = {
    .header.always_zero = 0,
    .header.w = 50,
    .header.h = 28,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_1883567225_load()
{
    ui_img_1883567225.data = UI_LOAD_IMAGE("F:assets/ui_img_1883567225.bin", 4200);
    ui_img_1883567225.data_size = 4200;
}
