// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"

lv_obj_t * ui_AutoSilenceNoPilot;
lv_obj_t * ui_DepthDropdown;
lv_obj_t * ui_SettingsCancel;
lv_obj_t * ui_SettingsOk;
lv_obj_t * ui_HeadingDampingSlider;
lv_obj_t * ui_WindDampingSlider;
lv_obj_t * ui_WindDropdown;
lv_obj_t * ui_DistanceDropdown;
lv_obj_t * ui_PostionDropdown;
lv_obj_t * ui_SpeedDropdown;
lv_obj_t * ui_SettingsScr;
lv_obj_t * ui_SettingsScr = NULL;
lv_obj_t * ui_POSpanel6 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_SpeedDropdown = NULL;
lv_obj_t * ui_PostionDropdown = NULL;
lv_obj_t * ui_DistanceDropdown = NULL;
lv_obj_t * ui_WindDropdown = NULL;
lv_obj_t * ui_Label36 = NULL;
lv_obj_t * ui_WindDampingSlider = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_HeadingDampingSlider = NULL;
lv_obj_t * ui_SettingsOk = NULL;
lv_obj_t * ui_SettingsCancel = NULL;
lv_obj_t * ui_DepthDropdown = NULL;
lv_obj_t * ui_AutoSilenceNoPilot = NULL;
// event funtions
void ui_event_SettingsOk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScrInfo, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScrInfo_screen_init);
        StoreUnitSettings(e);
    }
}

void ui_event_SettingsCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScrInfo, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScrInfo_screen_init);
        CancelUnitSettings(e);
    }
}

// build funtions

void ui_SettingsScr_screen_init(void)
{
    ui_SettingsScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_POSpanel6 = lv_obj_create(ui_SettingsScr);
    lv_obj_set_width(ui_POSpanel6, 460);
    lv_obj_set_height(ui_POSpanel6, 469);
    lv_obj_set_x(ui_POSpanel6, 8);
    lv_obj_set_y(ui_POSpanel6, 3);
    lv_obj_clear_flag(ui_POSpanel6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_POSpanel6, lv_color_hex(0x6A6D6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_POSpanel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_POSpanel6, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_POSpanel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_POSpanel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_POSpanel6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_POSpanel6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_POSpanel6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_POSpanel6);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 61);
    lv_obj_set_y(ui_Label23, 12);
    lv_label_set_text(ui_Label23, "Speed:");
    lv_obj_clear_flag(ui_Label23, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label31 = lv_label_create(ui_POSpanel6);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 50);
    lv_obj_set_y(ui_Label31, 67);
    lv_label_set_text(ui_Label31, "Position:");
    lv_obj_clear_flag(ui_Label31, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label33 = lv_label_create(ui_POSpanel6);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 48);
    lv_obj_set_y(ui_Label33, 122);
    lv_label_set_text(ui_Label33, "Distance:");
    lv_obj_clear_flag(ui_Label33, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label34 = lv_label_create(ui_POSpanel6);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, 73);
    lv_obj_set_y(ui_Label34, 177);
    lv_label_set_text(ui_Label34, "Wind:");
    lv_obj_clear_flag(ui_Label34, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label39 = lv_label_create(ui_POSpanel6);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, 68);
    lv_obj_set_y(ui_Label39, 232);
    lv_label_set_text(ui_Label39, "Depth:");
    lv_obj_clear_flag(ui_Label39, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label5 = lv_label_create(ui_POSpanel6);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -12);
    lv_obj_set_y(ui_Label5, -12);
    lv_label_set_text(ui_Label5, "s\ne\nt\nt\ni\nn\ng\ns");
    lv_obj_clear_flag(ui_Label5, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_letter_space(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label5, -5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label5, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label5, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label5, lv_color_hex(0xC6C6C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label5, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Label5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Label5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Label5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Label5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedDropdown = lv_dropdown_create(ui_SettingsScr);
    lv_dropdown_set_options(ui_SpeedDropdown, "Knots\nm/s\nkm/h");
    lv_obj_set_width(ui_SpeedDropdown, 265);
    lv_obj_set_height(ui_SpeedDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedDropdown, 173);
    lv_obj_set_y(ui_SpeedDropdown, 20);
    lv_obj_clear_flag(ui_SpeedDropdown, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);    /// Flags
    lv_obj_set_style_shadow_color(ui_SpeedDropdown, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SpeedDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SpeedDropdown, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SpeedDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SpeedDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SpeedDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PostionDropdown = lv_dropdown_create(ui_SettingsScr);
    lv_dropdown_set_options(ui_PostionDropdown, "Degrees Decimal Minutes\nDecimal Degrees\nDegrees Minutes Seconds");
    lv_obj_set_width(ui_PostionDropdown, 265);
    lv_obj_set_height(ui_PostionDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PostionDropdown, 173);
    lv_obj_set_y(ui_PostionDropdown, 75);
    lv_obj_clear_flag(ui_PostionDropdown,
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_shadow_color(ui_PostionDropdown, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PostionDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PostionDropdown, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PostionDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_PostionDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_PostionDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DistanceDropdown = lv_dropdown_create(ui_SettingsScr);
    lv_dropdown_set_options(ui_DistanceDropdown, "Nautical miles\nkilometer\nStatute miles");
    lv_obj_set_width(ui_DistanceDropdown, 265);
    lv_obj_set_height(ui_DistanceDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DistanceDropdown, 173);
    lv_obj_set_y(ui_DistanceDropdown, 130);
    lv_obj_clear_flag(ui_DistanceDropdown,
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_shadow_color(ui_DistanceDropdown, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_DistanceDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_DistanceDropdown, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_DistanceDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_DistanceDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_DistanceDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WindDropdown = lv_dropdown_create(ui_SettingsScr);
    lv_dropdown_set_options(ui_WindDropdown, "Knots\nm/s\nkm/h\nBeaufort");
    lv_obj_set_width(ui_WindDropdown, 265);
    lv_obj_set_height(ui_WindDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WindDropdown, 173);
    lv_obj_set_y(ui_WindDropdown, 185);
    lv_obj_add_flag(ui_WindDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_shadow_color(ui_WindDropdown, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WindDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WindDropdown, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WindDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_WindDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_WindDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_SettingsScr);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 32);
    lv_obj_set_y(ui_Label36, 330);
    lv_label_set_text(ui_Label36, "Wind damping:");
    lv_obj_clear_flag(ui_Label36, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_WindDampingSlider = lv_slider_create(ui_SettingsScr);
    lv_slider_set_value(ui_WindDampingSlider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_WindDampingSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_WindDampingSlider, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_WindDampingSlider, 260);
    lv_obj_set_height(ui_WindDampingSlider, 10);
    lv_obj_set_x(ui_WindDampingSlider, 173);
    lv_obj_set_y(ui_WindDampingSlider, 335);
    lv_obj_set_style_bg_color(ui_WindDampingSlider, lv_color_hex(0xD3D3D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WindDampingSlider, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WindDampingSlider, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WindDampingSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WindDampingSlider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WindDampingSlider, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WindDampingSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WindDampingSlider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WindDampingSlider, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_WindDampingSlider, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_WindDampingSlider, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WindDampingSlider, lv_color_hex(0xA29F9F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WindDampingSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_WindDampingSlider, lv_color_hex(0x3F3F3F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_WindDampingSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_WindDampingSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_WindDampingSlider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WindDampingSlider, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WindDampingSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WindDampingSlider, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WindDampingSlider, lv_color_hex(0x333333), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WindDampingSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_SettingsScr);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, 15);
    lv_obj_set_y(ui_Label35, 373);
    lv_label_set_text(ui_Label35, "Heading damping:");
    lv_obj_clear_flag(ui_Label35, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label37 = lv_label_create(ui_SettingsScr);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 175);
    lv_obj_set_y(ui_Label37, 344);
    lv_label_set_text(ui_Label37, "-                             + ");
    lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeadingDampingSlider = lv_slider_create(ui_SettingsScr);
    lv_slider_set_value(ui_HeadingDampingSlider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_HeadingDampingSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_HeadingDampingSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_HeadingDampingSlider, 260);
    lv_obj_set_height(ui_HeadingDampingSlider, 10);
    lv_obj_set_x(ui_HeadingDampingSlider, 173);
    lv_obj_set_y(ui_HeadingDampingSlider, 375);
    lv_obj_set_style_bg_color(ui_HeadingDampingSlider, lv_color_hex(0xD3D3D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeadingDampingSlider, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HeadingDampingSlider, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HeadingDampingSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HeadingDampingSlider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HeadingDampingSlider, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HeadingDampingSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_HeadingDampingSlider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_HeadingDampingSlider, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_HeadingDampingSlider, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_HeadingDampingSlider, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_HeadingDampingSlider, lv_color_hex(0xA29F9F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeadingDampingSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_HeadingDampingSlider, lv_color_hex(0x3F3F3F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_HeadingDampingSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_HeadingDampingSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_HeadingDampingSlider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HeadingDampingSlider, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HeadingDampingSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HeadingDampingSlider, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_HeadingDampingSlider, lv_color_hex(0x333333), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeadingDampingSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SettingsOk = lv_btn_create(ui_SettingsScr);
    lv_obj_set_width(ui_SettingsOk, 99);
    lv_obj_set_height(ui_SettingsOk, 55);
    lv_obj_set_x(ui_SettingsOk, 338);
    lv_obj_set_y(ui_SettingsOk, 409);
    lv_obj_clear_flag(ui_SettingsOk, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_SettingsOk, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingsOk, lv_color_hex(0x494949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SettingsOk, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SettingsOk, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SettingsOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SettingsOk, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SettingsOk, &ui_img_ok_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SettingsOk, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SettingsOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsOk, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SettingsOk, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SettingsOk, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SettingsOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SettingsOk, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SettingsOk, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SettingsOk, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SettingsOk, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SettingsOk, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsOk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsOk, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsCancel = lv_btn_create(ui_SettingsScr);
    lv_obj_set_width(ui_SettingsCancel, 99);
    lv_obj_set_height(ui_SettingsCancel, 55);
    lv_obj_set_x(ui_SettingsCancel, 34);
    lv_obj_set_y(ui_SettingsCancel, 409);
    lv_obj_clear_flag(ui_SettingsCancel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_SettingsCancel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingsCancel, lv_color_hex(0x494949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SettingsCancel, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SettingsCancel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SettingsCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SettingsCancel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SettingsCancel, &ui_img_cancel_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SettingsCancel, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SettingsCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsCancel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SettingsCancel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SettingsCancel, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SettingsCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SettingsCancel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SettingsCancel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SettingsCancel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SettingsCancel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SettingsCancel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsCancel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DepthDropdown = lv_dropdown_create(ui_SettingsScr);
    lv_dropdown_set_options(ui_DepthDropdown, "Meter\nFeet");
    lv_obj_set_width(ui_DepthDropdown, 265);
    lv_obj_set_height(ui_DepthDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DepthDropdown, 173);
    lv_obj_set_y(ui_DepthDropdown, 240);
    lv_obj_add_flag(ui_DepthDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_shadow_color(ui_DepthDropdown, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_DepthDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_DepthDropdown, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_DepthDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_DepthDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_DepthDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AutoSilenceNoPilot = lv_checkbox_create(ui_SettingsScr);
    lv_checkbox_set_text(ui_AutoSilenceNoPilot, "Silence No Pilot Warning");
    lv_obj_set_width(ui_AutoSilenceNoPilot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AutoSilenceNoPilot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AutoSilenceNoPilot, 173);
    lv_obj_set_y(ui_AutoSilenceNoPilot, 299);
    lv_obj_add_flag(ui_AutoSilenceNoPilot, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_border_color(ui_AutoSilenceNoPilot, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AutoSilenceNoPilot, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AutoSilenceNoPilot, lv_color_hex(0x8D8B8B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AutoSilenceNoPilot, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AutoSilenceNoPilot, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AutoSilenceNoPilot, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_AutoSilenceNoPilot, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_AutoSilenceNoPilot, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SettingsOk, ui_event_SettingsOk, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsCancel, ui_event_SettingsCancel, LV_EVENT_ALL, NULL);
    ui_SettingsScr = ui_SettingsScr;
    ui_SpeedDropdown = ui_SpeedDropdown;
    ui_PostionDropdown = ui_PostionDropdown;
    ui_DistanceDropdown = ui_DistanceDropdown;
    ui_WindDropdown = ui_WindDropdown;
    ui_WindDampingSlider = ui_WindDampingSlider;
    ui_HeadingDampingSlider = ui_HeadingDampingSlider;
    ui_SettingsOk = ui_SettingsOk;
    ui_SettingsCancel = ui_SettingsCancel;
    ui_DepthDropdown = ui_DepthDropdown;
    ui_AutoSilenceNoPilot = ui_AutoSilenceNoPilot;

}

void ui_SettingsScr_screen_destroy(void)
{
    if(ui_SettingsScr) lv_obj_del(ui_SettingsScr);

    // NULL screen variables
    ui_SettingsScr = NULL;
    ui_SettingsScr = NULL;
    ui_POSpanel6 = NULL;
    ui_Label23 = NULL;
    ui_Label31 = NULL;
    ui_Label33 = NULL;
    ui_Label34 = NULL;
    ui_Label39 = NULL;
    ui_Label5 = NULL;
    ui_SpeedDropdown = NULL;
    ui_SpeedDropdown = NULL;
    ui_PostionDropdown = NULL;
    ui_PostionDropdown = NULL;
    ui_DistanceDropdown = NULL;
    ui_DistanceDropdown = NULL;
    ui_WindDropdown = NULL;
    ui_WindDropdown = NULL;
    ui_Label36 = NULL;
    ui_WindDampingSlider = NULL;
    ui_WindDampingSlider = NULL;
    ui_Label35 = NULL;
    ui_Label37 = NULL;
    ui_HeadingDampingSlider = NULL;
    ui_HeadingDampingSlider = NULL;
    ui_SettingsOk = NULL;
    ui_SettingsOk = NULL;
    ui_SettingsCancel = NULL;
    ui_SettingsCancel = NULL;
    ui_DepthDropdown = NULL;
    ui_DepthDropdown = NULL;
    ui_AutoSilenceNoPilot = NULL;
    ui_AutoSilenceNoPilot = NULL;

}
