// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"

lv_obj_t * ui_ETWday;
lv_obj_t * ui_ETW;
lv_obj_t * ui_ETWpanel;
lv_obj_t * ui_DistanceLbl1;
lv_obj_t * ui_DistanceWpt;
lv_obj_t * ui_DTWpanel;
lv_obj_t * ui_DistanceLbl;
lv_obj_t * ui_XteWpt;
lv_obj_t * ui_XTEleft;
lv_obj_t * ui_XTEright;
lv_obj_t * ui_XTEpanel;
lv_obj_t * ui_BearingWpt;
lv_obj_t * ui_BTWpanel;
lv_obj_t * ui_BoatImg;
lv_obj_t * ui_HelmManPanel;
lv_obj_t * ui_ScrXTE;
lv_obj_t * ui_ScrXTE = NULL;
lv_obj_t * ui_HelmManPanel = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_BoatImg = NULL;
lv_obj_t * ui_BTWpanel = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_BearingWpt = NULL;
lv_obj_t * ui_XTEpanel = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_XTEright = NULL;
lv_obj_t * ui_XTEleft = NULL;
lv_obj_t * ui_XteWpt = NULL;
lv_obj_t * ui_DistanceLbl = NULL;
lv_obj_t * ui_DTWpanel = NULL;
lv_obj_t * ui_DistanceWpt = NULL;
lv_obj_t * ui_DistanceLbl1 = NULL;
lv_obj_t * ui_ETWpanel = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_ETW = NULL;
lv_obj_t * ui_ETWday = NULL;
// event funtions
void ui_event_ScrXTE(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrWind, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScrWind_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrNav, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScrNav_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrAutopilot, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_ScrAutopilot_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrAutopilot, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ScrAutopilot_screen_init);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        DoSetBacklight(e);
    }
}

// build funtions

void ui_ScrXTE_screen_init(void)
{
    ui_ScrXTE = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrXTE, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags

    ui_HelmManPanel = lv_obj_create(ui_ScrXTE);
    lv_obj_set_width(ui_HelmManPanel, 460);
    lv_obj_set_height(ui_HelmManPanel, 238);
    lv_obj_set_x(ui_HelmManPanel, 8);
    lv_obj_set_y(ui_HelmManPanel, 3);
    lv_obj_clear_flag(ui_HelmManPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_HelmManPanel, lv_color_hex(0x6A6D6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HelmManPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HelmManPanel, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HelmManPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_HelmManPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_HelmManPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_HelmManPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_HelmManPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_HelmManPanel);
    lv_img_set_src(ui_Image2, &ui_img_helmman_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 1);
    lv_obj_set_y(ui_Image2, -1);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_BoatImg = lv_img_create(ui_HelmManPanel);
    lv_img_set_src(ui_BoatImg, &ui_img_boat_png);
    lv_obj_set_width(ui_BoatImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BoatImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BoatImg, 0);
    lv_obj_set_y(ui_BoatImg, 137);
    lv_obj_set_align(ui_BoatImg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BoatImg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_BTWpanel = lv_obj_create(ui_ScrXTE);
    lv_obj_set_width(ui_BTWpanel, 225);
    lv_obj_set_height(ui_BTWpanel, 100);
    lv_obj_set_x(ui_BTWpanel, 8);
    lv_obj_set_y(ui_BTWpanel, 254);
    lv_obj_clear_flag(ui_BTWpanel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_BTWpanel, lv_color_hex(0x6A6D6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BTWpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTWpanel, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BTWpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BTWpanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BTWpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_BTWpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_BTWpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_BTWpanel);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -8);
    lv_obj_set_y(ui_Label7, -11);
    lv_label_set_text(ui_Label7, "BTW:");
    lv_obj_clear_flag(ui_Label7, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_BearingWpt = lv_label_create(ui_BTWpanel);
    lv_obj_set_width(ui_BearingWpt, 230);
    lv_obj_set_height(ui_BearingWpt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BearingWpt, 0);
    lv_obj_set_y(ui_BearingWpt, 4);
    lv_obj_set_align(ui_BearingWpt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BearingWpt, "---°");
    lv_obj_clear_flag(ui_BearingWpt, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_BearingWpt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BearingWpt, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_XTEpanel = lv_obj_create(ui_ScrXTE);
    lv_obj_set_width(ui_XTEpanel, 225);
    lv_obj_set_height(ui_XTEpanel, 100);
    lv_obj_set_x(ui_XTEpanel, 243);
    lv_obj_set_y(ui_XTEpanel, 254);
    lv_obj_clear_flag(ui_XTEpanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_XTEpanel, lv_color_hex(0x6A6D6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_XTEpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_XTEpanel, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_XTEpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_XTEpanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_XTEpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_XTEpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_XTEpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_XTEpanel);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -1);
    lv_obj_set_y(ui_Label4, -35);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "|");
    lv_obj_clear_flag(ui_Label4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFE0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_XTEright = lv_img_create(ui_XTEpanel);
    lv_img_set_src(ui_XTEright, &ui_img_1883567225);
    lv_obj_set_width(ui_XTEright, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_XTEright, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_XTEright, 24);
    lv_obj_set_y(ui_XTEright, -34);
    lv_obj_set_align(ui_XTEright, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_XTEright, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_XTEleft = lv_img_create(ui_XTEpanel);
    lv_img_set_src(ui_XTEleft, &ui_img_1883567225);
    lv_obj_set_width(ui_XTEleft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_XTEleft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_XTEleft, -27);
    lv_obj_set_y(ui_XTEleft, -34);
    lv_obj_set_align(ui_XTEleft, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_XTEleft, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_angle(ui_XTEleft, 1800);

    ui_XteWpt = lv_label_create(ui_XTEpanel);
    lv_obj_set_width(ui_XteWpt, 230);
    lv_obj_set_height(ui_XteWpt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_XteWpt, -1);
    lv_obj_set_y(ui_XteWpt, 20);
    lv_obj_set_align(ui_XteWpt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_XteWpt, "--.-");
    lv_obj_clear_flag(ui_XteWpt, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_XteWpt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_XteWpt, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DistanceLbl = lv_label_create(ui_XTEpanel);
    lv_obj_set_width(ui_DistanceLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DistanceLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DistanceLbl, -8);
    lv_obj_set_y(ui_DistanceLbl, -11);
    lv_label_set_text(ui_DistanceLbl, "XTE:                                     nm");
    lv_obj_clear_flag(ui_DistanceLbl, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_DTWpanel = lv_obj_create(ui_ScrXTE);
    lv_obj_set_width(ui_DTWpanel, 225);
    lv_obj_set_height(ui_DTWpanel, 100);
    lv_obj_set_x(ui_DTWpanel, 8);
    lv_obj_set_y(ui_DTWpanel, 366);
    lv_obj_clear_flag(ui_DTWpanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_DTWpanel, lv_color_hex(0x6A6D6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DTWpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_DTWpanel, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_DTWpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_DTWpanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_DTWpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_DTWpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_DTWpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DistanceWpt = lv_label_create(ui_DTWpanel);
    lv_obj_set_width(ui_DistanceWpt, 230);
    lv_obj_set_height(ui_DistanceWpt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DistanceWpt, 0);
    lv_obj_set_y(ui_DistanceWpt, 4);
    lv_obj_set_align(ui_DistanceWpt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DistanceWpt, "--.-");
    lv_obj_clear_flag(ui_DistanceWpt, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_DistanceWpt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DistanceWpt, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DistanceLbl1 = lv_label_create(ui_DTWpanel);
    lv_obj_set_width(ui_DistanceLbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DistanceLbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DistanceLbl1, -8);
    lv_obj_set_y(ui_DistanceLbl1, -11);
    lv_label_set_text(ui_DistanceLbl1, "DTW:                                   nm");
    lv_obj_clear_flag(ui_DistanceLbl1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_DistanceLbl1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ETWpanel = lv_obj_create(ui_ScrXTE);
    lv_obj_set_width(ui_ETWpanel, 225);
    lv_obj_set_height(ui_ETWpanel, 100);
    lv_obj_set_x(ui_ETWpanel, 243);
    lv_obj_set_y(ui_ETWpanel, 366);
    lv_obj_clear_flag(ui_ETWpanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_ETWpanel, lv_color_hex(0x6A6D6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ETWpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ETWpanel, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ETWpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ETWpanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ETWpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ETWpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ETWpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_ETWpanel);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -8);
    lv_obj_set_y(ui_Label11, -11);
    lv_label_set_text(ui_Label11, "ETW:");
    lv_obj_clear_flag(ui_Label11, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_ETW = lv_label_create(ui_ETWpanel);
    lv_obj_set_width(ui_ETW, 230);
    lv_obj_set_height(ui_ETW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ETW, 0);
    lv_obj_set_y(ui_ETW, 4);
    lv_obj_set_align(ui_ETW, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ETW, "--:--");
    lv_obj_clear_flag(ui_ETW, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_ETW, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ETW, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ETWday = lv_label_create(ui_ETWpanel);
    lv_obj_set_width(ui_ETWday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ETWday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ETWday, 69);
    lv_obj_set_y(ui_ETWday, -35);
    lv_obj_set_align(ui_ETWday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ETWday, "Day + --");
    lv_obj_clear_flag(ui_ETWday, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    lv_obj_add_event_cb(ui_ScrXTE, ui_event_ScrXTE, LV_EVENT_ALL, NULL);
    ui_ScrXTE = ui_ScrXTE;
    ui_HelmManPanel = ui_HelmManPanel;
    ui_BoatImg = ui_BoatImg;
    ui_BTWpanel = ui_BTWpanel;
    ui_BearingWpt = ui_BearingWpt;
    ui_XTEpanel = ui_XTEpanel;
    ui_XTEright = ui_XTEright;
    ui_XTEleft = ui_XTEleft;
    ui_XteWpt = ui_XteWpt;
    ui_DistanceLbl = ui_DistanceLbl;
    ui_DTWpanel = ui_DTWpanel;
    ui_DistanceWpt = ui_DistanceWpt;
    ui_DistanceLbl1 = ui_DistanceLbl1;
    ui_ETWpanel = ui_ETWpanel;
    ui_ETW = ui_ETW;
    ui_ETWday = ui_ETWday;

}

void ui_ScrXTE_screen_destroy(void)
{
    if(ui_ScrXTE) lv_obj_del(ui_ScrXTE);

    // NULL screen variables
    ui_ScrXTE = NULL;
    ui_ScrXTE = NULL;
    ui_HelmManPanel = NULL;
    ui_HelmManPanel = NULL;
    ui_Image2 = NULL;
    ui_BoatImg = NULL;
    ui_BoatImg = NULL;
    ui_BTWpanel = NULL;
    ui_BTWpanel = NULL;
    ui_Label7 = NULL;
    ui_BearingWpt = NULL;
    ui_BearingWpt = NULL;
    ui_XTEpanel = NULL;
    ui_XTEpanel = NULL;
    ui_Label4 = NULL;
    ui_XTEright = NULL;
    ui_XTEright = NULL;
    ui_XTEleft = NULL;
    ui_XTEleft = NULL;
    ui_XteWpt = NULL;
    ui_XteWpt = NULL;
    ui_DistanceLbl = NULL;
    ui_DistanceLbl = NULL;
    ui_DTWpanel = NULL;
    ui_DTWpanel = NULL;
    ui_DistanceWpt = NULL;
    ui_DistanceWpt = NULL;
    ui_DistanceLbl1 = NULL;
    ui_DistanceLbl1 = NULL;
    ui_ETWpanel = NULL;
    ui_ETWpanel = NULL;
    ui_Label11 = NULL;
    ui_ETW = NULL;
    ui_ETW = NULL;
    ui_ETWday = NULL;
    ui_ETWday = NULL;

}
