// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"

lv_obj_t * ui_AutopilotHeading1;
lv_obj_t * ui_APmode1;
lv_obj_t * ui_SpeedLbl1;
lv_obj_t * ui_STW;
lv_obj_t * ui_HDG;
lv_obj_t * ui_PosLbl;
lv_obj_t * ui_Lon;
lv_obj_t * ui_Lat;
lv_obj_t * ui_ScrNav;
lv_obj_t * ui_ScrNav = NULL;
lv_obj_t * ui_POSpanel = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Lat = NULL;
lv_obj_t * ui_Lon = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_PosLbl = NULL;
lv_obj_t * ui_HDGpanel = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_HDG = NULL;
lv_obj_t * ui_STWpanel = NULL;
lv_obj_t * ui_STW = NULL;
lv_obj_t * ui_SpeedLbl1 = NULL;
lv_obj_t * ui_POSpanel4 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_APmode1 = NULL;
lv_obj_t * ui_AutopilotHeading1 = NULL;
// event funtions
void ui_event_ScrNav(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrAutopilot, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScrAutopilot_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrWind, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScrWind_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrInfo, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ScrInfo_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrInfo, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_ScrInfo_screen_init);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        DoSetBacklight(e);
    }
}

// build funtions

void ui_ScrNav_screen_init(void)
{
    ui_ScrNav = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrNav, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags

    ui_POSpanel = lv_obj_create(ui_ScrNav);
    lv_obj_set_width(ui_POSpanel, 460);
    lv_obj_set_height(ui_POSpanel, 206);
    lv_obj_set_x(ui_POSpanel, 8);
    lv_obj_set_y(ui_POSpanel, 3);
    lv_obj_clear_flag(ui_POSpanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_POSpanel, lv_color_hex(0x6A6D6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_POSpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_POSpanel, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_POSpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_POSpanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_POSpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_POSpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_POSpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_POSpanel);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -8);
    lv_obj_set_y(ui_Label13, -4);
    lv_label_set_text(ui_Label13, "Lat:");
    lv_obj_clear_flag(ui_Label13, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Lat = lv_label_create(ui_POSpanel);
    lv_obj_set_width(ui_Lat, 424);
    lv_obj_set_height(ui_Lat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lat, 0);
    lv_obj_set_y(ui_Lat, -50);
    lv_obj_set_align(ui_Lat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Lat, "--.----°-");
    lv_obj_clear_flag(ui_Lat, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Lat, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Lat, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lon = lv_label_create(ui_POSpanel);
    lv_obj_set_width(ui_Lon, 424);
    lv_obj_set_height(ui_Lon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lon, 0);
    lv_obj_set_y(ui_Lon, 43);
    lv_obj_set_align(ui_Lon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Lon, "---.----°-");
    lv_obj_clear_flag(ui_Lon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Lon, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Lon, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_POSpanel);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -8);
    lv_obj_set_y(ui_Label12, 90);
    lv_label_set_text(ui_Label12, "Lon:");
    lv_obj_clear_flag(ui_Label12, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_PosLbl = lv_label_create(ui_POSpanel);
    lv_obj_set_width(ui_PosLbl, 300);
    lv_obj_set_height(ui_PosLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PosLbl, 128);
    lv_obj_set_y(ui_PosLbl, 162);
    lv_label_set_text(ui_PosLbl, "DDM: Degrees Decimal Minutes");
    lv_obj_clear_flag(ui_PosLbl, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_PosLbl, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HDGpanel = lv_obj_create(ui_ScrNav);
    lv_obj_set_width(ui_HDGpanel, 225);
    lv_obj_set_height(ui_HDGpanel, 137);
    lv_obj_set_x(ui_HDGpanel, 243);
    lv_obj_set_y(ui_HDGpanel, 330);
    lv_obj_clear_flag(ui_HDGpanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_HDGpanel, lv_color_hex(0x6A6D6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HDGpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HDGpanel, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HDGpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_HDGpanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_HDGpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_HDGpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_HDGpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_HDGpanel);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -8);
    lv_obj_set_y(ui_Label16, -11);
    lv_label_set_text(ui_Label16, "HDG:");
    lv_obj_clear_flag(ui_Label16, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_HDG = lv_label_create(ui_HDGpanel);
    lv_obj_set_width(ui_HDG, 232);
    lv_obj_set_height(ui_HDG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HDG, 0);
    lv_obj_set_y(ui_HDG, 4);
    lv_obj_set_align(ui_HDG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HDG, "---°");
    lv_obj_clear_flag(ui_HDG, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_HDG, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HDG, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STWpanel = lv_obj_create(ui_ScrNav);
    lv_obj_set_width(ui_STWpanel, 225);
    lv_obj_set_height(ui_STWpanel, 137);
    lv_obj_set_x(ui_STWpanel, 8);
    lv_obj_set_y(ui_STWpanel, 330);
    lv_obj_clear_flag(ui_STWpanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_STWpanel, lv_color_hex(0x6A6D6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_STWpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_STWpanel, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_STWpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_STWpanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_STWpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_STWpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_STWpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STW = lv_label_create(ui_STWpanel);
    lv_obj_set_width(ui_STW, 232);
    lv_obj_set_height(ui_STW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STW, 1);
    lv_obj_set_y(ui_STW, 4);
    lv_obj_set_align(ui_STW, LV_ALIGN_CENTER);
    lv_label_set_text(ui_STW, "--.-");
    lv_obj_clear_flag(ui_STW, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_STW, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_STW, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_STW, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedLbl1 = lv_label_create(ui_STWpanel);
    lv_obj_set_width(ui_SpeedLbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedLbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedLbl1, -8);
    lv_obj_set_y(ui_SpeedLbl1, -11);
    lv_label_set_text(ui_SpeedLbl1, "STW:                                  kn");
    lv_obj_clear_flag(ui_SpeedLbl1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_POSpanel4 = lv_obj_create(ui_ScrNav);
    lv_obj_set_width(ui_POSpanel4, 460);
    lv_obj_set_height(ui_POSpanel4, 96);
    lv_obj_set_x(ui_POSpanel4, 8);
    lv_obj_set_y(ui_POSpanel4, 222);
    lv_obj_clear_flag(ui_POSpanel4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_POSpanel4, lv_color_hex(0x6A6D6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_POSpanel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_POSpanel4, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_POSpanel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_POSpanel4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_POSpanel4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_POSpanel4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_POSpanel4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_POSpanel4);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -8);
    lv_obj_set_y(ui_Label17, -6);
    lv_label_set_text(ui_Label17, "Autopilot:");
    lv_obj_clear_flag(ui_Label17, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_APmode1 = lv_label_create(ui_POSpanel4);
    lv_obj_set_width(ui_APmode1, 250);
    lv_obj_set_height(ui_APmode1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_APmode1, -92);
    lv_obj_set_y(ui_APmode1, 6);
    lv_obj_set_align(ui_APmode1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_APmode1, "--------");
    lv_obj_clear_flag(ui_APmode1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_APmode1, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AutopilotHeading1 = lv_label_create(ui_POSpanel4);
    lv_obj_set_width(ui_AutopilotHeading1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AutopilotHeading1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AutopilotHeading1, 103);
    lv_obj_set_y(ui_AutopilotHeading1, 0);
    lv_obj_set_align(ui_AutopilotHeading1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AutopilotHeading1, "---°");
    lv_obj_clear_flag(ui_AutopilotHeading1,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_AutopilotHeading1, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScrNav, ui_event_ScrNav, LV_EVENT_ALL, NULL);
    ui_ScrNav = ui_ScrNav;
    ui_Lat = ui_Lat;
    ui_Lon = ui_Lon;
    ui_PosLbl = ui_PosLbl;
    ui_HDG = ui_HDG;
    ui_STW = ui_STW;
    ui_SpeedLbl1 = ui_SpeedLbl1;
    ui_APmode1 = ui_APmode1;
    ui_AutopilotHeading1 = ui_AutopilotHeading1;

}

void ui_ScrNav_screen_destroy(void)
{
    if(ui_ScrNav) lv_obj_del(ui_ScrNav);

    // NULL screen variables
    ui_ScrNav = NULL;
    ui_ScrNav = NULL;
    ui_POSpanel = NULL;
    ui_Label13 = NULL;
    ui_Lat = NULL;
    ui_Lat = NULL;
    ui_Lon = NULL;
    ui_Lon = NULL;
    ui_Label12 = NULL;
    ui_PosLbl = NULL;
    ui_PosLbl = NULL;
    ui_HDGpanel = NULL;
    ui_Label16 = NULL;
    ui_HDG = NULL;
    ui_HDG = NULL;
    ui_STWpanel = NULL;
    ui_STW = NULL;
    ui_STW = NULL;
    ui_SpeedLbl1 = NULL;
    ui_SpeedLbl1 = NULL;
    ui_POSpanel4 = NULL;
    ui_Label17 = NULL;
    ui_APmode1 = NULL;
    ui_APmode1 = NULL;
    ui_AutopilotHeading1 = NULL;
    ui_AutopilotHeading1 = NULL;

}
