// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"

lv_obj_t * ui_SplashScr;
lv_obj_t * ui_SplashScr = NULL;
// event funtions
void ui_event_SplashScr(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_ScrWind, LV_SCR_LOAD_ANIM_NONE, 200, 2000, &ui_ScrWind_screen_init);
    }
}

// build funtions

void ui_SplashScr_screen_init(void)
{
    ui_SplashScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SplashScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_SplashScr, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_SplashScr_screen_destroy);
    lv_obj_set_style_bg_img_src(ui_SplashScr, &ui_img_splash_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SplashScr, ui_event_SplashScr, LV_EVENT_ALL, NULL);
    ui_SplashScr = ui_SplashScr;

}

void ui_SplashScr_screen_destroy(void)
{
    if(ui_SplashScr) lv_obj_del(ui_SplashScr);

    // NULL screen variables
    ui_SplashScr = NULL;
    ui_SplashScr = NULL;

}
