// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"

lv_obj_t * ui_AuthorLbl;
lv_obj_t * ui_Go2SettingScr;
lv_obj_t * ui_AWA;
lv_obj_t * ui_COG;
lv_obj_t * ui_SpeedLbl;
lv_obj_t * ui_SOG;
lv_obj_t * ui_Rudder1;
lv_obj_t * ui_DepthLbl;
lv_obj_t * ui_Depth;
lv_obj_t * ui_ScrInfo;
lv_obj_t * ui_ScrInfo = NULL;
lv_obj_t * ui_POSpanel3 = NULL;
lv_obj_t * ui_Depth = NULL;
lv_obj_t * ui_DepthLbl = NULL;
lv_obj_t * ui_POSpanel2 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Rudder1 = NULL;
lv_obj_t * ui_SOGpanel2 = NULL;
lv_obj_t * ui_SOG = NULL;
lv_obj_t * ui_SpeedLbl = NULL;
lv_obj_t * ui_HDGpanel2 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_COG = NULL;
lv_obj_t * ui_POSpanel5 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_AWA = NULL;
lv_obj_t * ui_Go2SettingScr = NULL;
lv_obj_t * ui_Auto2 = NULL;
lv_obj_t * ui_AuthorLbl = NULL;
// event funtions
void ui_event_ScrInfo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrNav, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ScrNav_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrNav, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_ScrNav_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrAutopilot, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScrAutopilot_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrWind, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScrWind_screen_init);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        DoSetBacklight(e);
    }
}

void ui_event_Go2SettingScr(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        DoInitSettingsScr(e);
    }
}

// build funtions

void ui_ScrInfo_screen_init(void)
{
    ui_ScrInfo = lv_obj_create(NULL);
    lv_obj_add_flag(ui_ScrInfo, LV_OBJ_FLAG_SCROLL_WITH_ARROW | LV_OBJ_FLAG_SCROLL_ONE);     /// Flags

    ui_POSpanel3 = lv_obj_create(ui_ScrInfo);
    lv_obj_set_width(ui_POSpanel3, 225);
    lv_obj_set_height(ui_POSpanel3, 137);
    lv_obj_set_x(ui_POSpanel3, 8);
    lv_obj_set_y(ui_POSpanel3, 3);
    lv_obj_clear_flag(ui_POSpanel3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_POSpanel3, lv_color_hex(0x6A6D6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_POSpanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_POSpanel3, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_POSpanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_POSpanel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_POSpanel3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_POSpanel3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_POSpanel3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Depth = lv_label_create(ui_POSpanel3);
    lv_obj_set_width(ui_Depth, 225);
    lv_obj_set_height(ui_Depth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Depth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Depth, "---.-");
    lv_obj_clear_flag(ui_Depth, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Depth, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Depth, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DepthLbl = lv_label_create(ui_POSpanel3);
    lv_obj_set_width(ui_DepthLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DepthLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DepthLbl, -8);
    lv_obj_set_y(ui_DepthLbl, -11);
    lv_label_set_text(ui_DepthLbl, "Depth:                                m");
    lv_obj_clear_flag(ui_DepthLbl, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_POSpanel2 = lv_obj_create(ui_ScrInfo);
    lv_obj_set_width(ui_POSpanel2, 460);
    lv_obj_set_height(ui_POSpanel2, 96);
    lv_obj_set_x(ui_POSpanel2, 8);
    lv_obj_set_y(ui_POSpanel2, 150);
    lv_obj_clear_flag(ui_POSpanel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_POSpanel2, lv_color_hex(0x6A6D6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_POSpanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_POSpanel2, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_POSpanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_POSpanel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_POSpanel2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_POSpanel2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_POSpanel2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_POSpanel2);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -8);
    lv_obj_set_y(ui_Label27, -1);
    lv_label_set_text(ui_Label27, "Rudder:");
    lv_obj_clear_flag(ui_Label27, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Rudder1 = lv_bar_create(ui_POSpanel2);
    lv_bar_set_mode(ui_Rudder1, LV_BAR_MODE_SYMMETRICAL);
    lv_bar_set_range(ui_Rudder1, -30, 30);
    lv_obj_set_width(ui_Rudder1, 382);
    lv_obj_set_height(ui_Rudder1, 30);
    lv_obj_set_x(ui_Rudder1, 0);
    lv_obj_set_y(ui_Rudder1, 11);
    lv_obj_set_align(ui_Rudder1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Rudder1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Rudder1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Rudder1, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Rudder1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Rudder1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Rudder1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Rudder1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Rudder1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Rudder1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Rudder1, lv_color_hex(0xFB0202), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Rudder1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Rudder1, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Rudder1, 127, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Rudder1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Rudder1, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Rudder1, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Rudder1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Rudder1, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SOGpanel2 = lv_obj_create(ui_ScrInfo);
    lv_obj_set_width(ui_SOGpanel2, 225);
    lv_obj_set_height(ui_SOGpanel2, 137);
    lv_obj_set_x(ui_SOGpanel2, 8);
    lv_obj_set_y(ui_SOGpanel2, 258);
    lv_obj_clear_flag(ui_SOGpanel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_SOGpanel2, lv_color_hex(0x6A6D6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SOGpanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SOGpanel2, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SOGpanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SOGpanel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SOGpanel2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SOGpanel2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SOGpanel2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOG = lv_label_create(ui_SOGpanel2);
    lv_obj_set_width(ui_SOG, 232);
    lv_obj_set_height(ui_SOG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SOG, 2);
    lv_obj_set_y(ui_SOG, -4);
    lv_obj_set_align(ui_SOG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOG, "--.-");
    lv_obj_clear_flag(ui_SOG, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_SOG, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_SOG, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SOG, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedLbl = lv_label_create(ui_SOGpanel2);
    lv_obj_set_width(ui_SpeedLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedLbl, -8);
    lv_obj_set_y(ui_SpeedLbl, -11);
    lv_label_set_text(ui_SpeedLbl, "SOG:                                  kn");
    lv_obj_clear_flag(ui_SpeedLbl, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_HDGpanel2 = lv_obj_create(ui_ScrInfo);
    lv_obj_set_width(ui_HDGpanel2, 225);
    lv_obj_set_height(ui_HDGpanel2, 137);
    lv_obj_set_x(ui_HDGpanel2, 243);
    lv_obj_set_y(ui_HDGpanel2, 258);
    lv_obj_clear_flag(ui_HDGpanel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_HDGpanel2, lv_color_hex(0x6A6D6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HDGpanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HDGpanel2, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HDGpanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_HDGpanel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_HDGpanel2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_HDGpanel2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_HDGpanel2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_HDGpanel2);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -8);
    lv_obj_set_y(ui_Label29, -11);
    lv_label_set_text(ui_Label29, "COG:");
    lv_obj_clear_flag(ui_Label29, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_COG = lv_label_create(ui_HDGpanel2);
    lv_obj_set_width(ui_COG, 232);
    lv_obj_set_height(ui_COG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_COG, 2);
    lv_obj_set_y(ui_COG, -4);
    lv_obj_set_align(ui_COG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_COG, "---°");
    lv_obj_clear_flag(ui_COG, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_COG, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_COG, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POSpanel5 = lv_obj_create(ui_ScrInfo);
    lv_obj_set_width(ui_POSpanel5, 225);
    lv_obj_set_height(ui_POSpanel5, 137);
    lv_obj_set_x(ui_POSpanel5, 243);
    lv_obj_set_y(ui_POSpanel5, 3);
    lv_obj_clear_flag(ui_POSpanel5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_POSpanel5, lv_color_hex(0x6A6D6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_POSpanel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_POSpanel5, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_POSpanel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_POSpanel5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_POSpanel5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_POSpanel5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_POSpanel5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_POSpanel5);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -8);
    lv_obj_set_y(ui_Label30, -11);
    lv_label_set_text(ui_Label30, "AWA: ");
    lv_obj_clear_flag(ui_Label30, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_AWA = lv_label_create(ui_POSpanel5);
    lv_obj_set_width(ui_AWA, 232);
    lv_obj_set_height(ui_AWA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AWA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AWA, "---°");
    lv_obj_clear_flag(ui_AWA, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_AWA, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AWA, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Go2SettingScr = lv_btn_create(ui_ScrInfo);
    lv_obj_set_width(ui_Go2SettingScr, 99);
    lv_obj_set_height(ui_Go2SettingScr, 60);
    lv_obj_set_x(ui_Go2SettingScr, 370);
    lv_obj_set_y(ui_Go2SettingScr, 406);
    lv_obj_clear_flag(ui_Go2SettingScr, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Go2SettingScr, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Go2SettingScr, lv_color_hex(0x494949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Go2SettingScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Go2SettingScr, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Go2SettingScr, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Go2SettingScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Go2SettingScr, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Go2SettingScr, &ui_img_settings_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Go2SettingScr, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Go2SettingScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Go2SettingScr, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Go2SettingScr, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Go2SettingScr, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Go2SettingScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Go2SettingScr, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Go2SettingScr, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Go2SettingScr, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Go2SettingScr, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Go2SettingScr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Go2SettingScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Go2SettingScr, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Auto2 = lv_btn_create(ui_ScrInfo);
    lv_obj_set_width(ui_Auto2, 351);
    lv_obj_set_height(ui_Auto2, 60);
    lv_obj_set_x(ui_Auto2, 8);
    lv_obj_set_y(ui_Auto2, 406);
    lv_obj_clear_flag(ui_Auto2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Auto2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Auto2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Auto2, lv_color_hex(0x3F1FC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Auto2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Auto2, lv_color_hex(0x96BEFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Auto2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Auto2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Auto2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Auto2, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Auto2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Auto2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Auto2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Auto2, lv_color_hex(0x8D8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Auto2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Auto2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Auto2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Auto2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Auto2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Auto2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Auto2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Auto2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Auto2, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Auto2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_Auto2, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Auto2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Auto2, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Auto2, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Auto2, lv_color_hex(0x878787), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Auto2, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_grad_color(ui_Auto2, lv_color_hex(0xBABABA), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_grad_dir(ui_Auto2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_outline_color(ui_Auto2, lv_color_hex(0x00FF80), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_outline_opa(ui_Auto2, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_outline_width(ui_Auto2, 5, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_outline_pad(ui_Auto2, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_Auto2, lv_color_hex(0x00FF80), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_Auto2, 255, LV_PART_MAIN | LV_STATE_USER_1);

    ui_AuthorLbl = lv_label_create(ui_Auto2);
    lv_obj_set_width(ui_AuthorLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AuthorLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AuthorLbl, -2);
    lv_obj_set_y(ui_AuthorLbl, 0);
    lv_obj_set_align(ui_AuthorLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AuthorLbl, "MicroShip by Francis Verhelst");
    lv_obj_clear_flag(ui_AuthorLbl, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_AuthorLbl, &ui_font_HandWriting24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Go2SettingScr, ui_event_Go2SettingScr, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrInfo, ui_event_ScrInfo, LV_EVENT_ALL, NULL);
    ui_ScrInfo = ui_ScrInfo;
    ui_Depth = ui_Depth;
    ui_DepthLbl = ui_DepthLbl;
    ui_Rudder1 = ui_Rudder1;
    ui_SOG = ui_SOG;
    ui_SpeedLbl = ui_SpeedLbl;
    ui_COG = ui_COG;
    ui_AWA = ui_AWA;
    ui_Go2SettingScr = ui_Go2SettingScr;
    ui_AuthorLbl = ui_AuthorLbl;

}

void ui_ScrInfo_screen_destroy(void)
{
    if(ui_ScrInfo) lv_obj_del(ui_ScrInfo);

    // NULL screen variables
    ui_ScrInfo = NULL;
    ui_ScrInfo = NULL;
    ui_POSpanel3 = NULL;
    ui_Depth = NULL;
    ui_Depth = NULL;
    ui_DepthLbl = NULL;
    ui_DepthLbl = NULL;
    ui_POSpanel2 = NULL;
    ui_Label27 = NULL;
    ui_Rudder1 = NULL;
    ui_Rudder1 = NULL;
    ui_SOGpanel2 = NULL;
    ui_SOG = NULL;
    ui_SOG = NULL;
    ui_SpeedLbl = NULL;
    ui_SpeedLbl = NULL;
    ui_HDGpanel2 = NULL;
    ui_Label29 = NULL;
    ui_COG = NULL;
    ui_COG = NULL;
    ui_POSpanel5 = NULL;
    ui_Label30 = NULL;
    ui_AWA = NULL;
    ui_AWA = NULL;
    ui_Go2SettingScr = NULL;
    ui_Go2SettingScr = NULL;
    ui_Auto2 = NULL;
    ui_AuthorLbl = NULL;
    ui_AuthorLbl = NULL;

}
